/*************************************************************
** Class generated by CodeTrigger, Version 6.3.0.4
** This class was generated on 2020-08-01 3:54:27 AM
** Changes to this file may cause incorrect behaviour and will be lost if the code is regenerated
**************************************************************/
using System;
using System.Diagnostics;
using System.ComponentModel;
namespace AAF.MVVMSample.ViewModel
{
	public partial interface IViewModelBase
	{
		void SaveCurrentView();
		void LoadRecords();
		int GetLoadCount();
		string DisplayName { get; set; }
	}
}

