/*************************************************************
** Class generated by CodeTrigger, Version 6.3.0.4
** This class was generated on 2020-08-01 3:54:27 AM
** Changes to this file may cause incorrect behaviour and will be lost if the code is regenerated
**************************************************************/
using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using AAF.BusinessObjects;
using Expr = AAF.BusinessObjects;

namespace AAF.MVVMSample.ViewModel
{
	public partial class LocationViewModel : IViewModelBase
	{
		/*WARNING - This class was generated by CodeTrigger. Changes to this file may cause incorrect behaviour and will be lost when the code is regenerated*/
		#region members
		private string _displayName = "Location";
		private readonly BOLocation _searchBO = new BOLocation();
		private readonly ObservableCollection<BOLocation> _boLocations = new ObservableCollection<BOLocation>();
		private IList<BOLocation> _boLocationsCached = new List<BOLocation>();
		private IList<BOLocation> _boLocationsCachedDelete = new List<BOLocation>();
		private RelayCommand _deleteRowCommand;
		#endregion
		
		#region constructor
		public LocationViewModel()
		{		}
		#endregion
		
		#region methods
		public static IList<BOLocation> GetLocationList()
		{
			try
			{
				IList<BOLocation> listLocation = BOLocation.LocationCollection();
				return listLocation;
			}
			catch(Exception)
			{	/*rethrow or handle gracefully*/return null;	}
			finally	{	}
		}
		
		private void AddExpr(ref Criteria<BOLocation> crit, string propertyName, object propertyValue, string propertyValueText, Func<object, string> formatter = null)
		{
			bool wildcard = propertyValueText.Contains("%");
			crit.Add(wildcard
				? Expression.Like(propertyName, propertyValue, formatter)
				: Expression.Eq(propertyName, propertyValue, formatter));
		}

		public int GetLoadCount()
		{
			var crit = new Criteria<BOLocation>();
			try
			{
				if(_searchBO.Id.HasValue) AddExpr(ref crit, "Id", _searchBO.Id, "" );
				if(_searchBO.Unit.HasValue) AddExpr(ref crit, "Unit", _searchBO.Unit, "" );
				if(!string.IsNullOrEmpty(_searchBO.PostalCode)) AddExpr(ref crit, "PostalCode", _searchBO.PostalCode, _searchBO.PostalCode);
				if(!string.IsNullOrEmpty(_searchBO.StreetName)) AddExpr(ref crit, "StreetName", _searchBO.StreetName, _searchBO.StreetName);
				if(!string.IsNullOrEmpty(_searchBO.Link)) AddExpr(ref crit, "Link", _searchBO.Link, _searchBO.Link);
				if(!string.IsNullOrEmpty(_searchBO.LatLong)) AddExpr(ref crit, "LatLong", _searchBO.LatLong, _searchBO.LatLong);
				int resultCount = crit.Count();
				return resultCount;
			}
			catch	{	throw;	}
			finally	{	}
		}
		
		public void LoadRecords()
		{
			var crit = new Criteria<BOLocation>();
			try
			{
				if(_searchBO.Id.HasValue) AddExpr(ref crit, "Id", _searchBO.Id, "" );
				if(_searchBO.Unit.HasValue) AddExpr(ref crit, "Unit", _searchBO.Unit, "" );
				if(!string.IsNullOrEmpty(_searchBO.PostalCode)) AddExpr(ref crit, "PostalCode", _searchBO.PostalCode, _searchBO.PostalCode);
				if(!string.IsNullOrEmpty(_searchBO.StreetName)) AddExpr(ref crit, "StreetName", _searchBO.StreetName, _searchBO.StreetName);
				if(!string.IsNullOrEmpty(_searchBO.Link)) AddExpr(ref crit, "Link", _searchBO.Link, _searchBO.Link);
				if(!string.IsNullOrEmpty(_searchBO.LatLong)) AddExpr(ref crit, "LatLong", _searchBO.LatLong, _searchBO.LatLong);
				
				_boLocations.Clear();
				_boLocationsCachedDelete.Clear();
				_boLocationsCached = crit.List<BOLocation>();
				foreach(BOLocation boLocation in _boLocationsCached)
					_boLocations.Add(boLocation);
			}
			catch	{	throw;	}
			finally	{	}
		}
		
		public void SaveCurrentView()
		{
			try
			{
				foreach(BOLocation boLocation in _boLocations)
				{
					if(_boLocationsCached.Contains(boLocation))
					{
						if(!boLocation.IsDirty) continue;
						try{ boLocation.Update(); }
						catch(Exception ex)
						{ throw new Exception("Error updating record: CodeTrigger has detected a data exception. Possible invalid foreign key reference, missing fields or other error. Exception details follow below.\r\n\r\n" + ex.Message); }
					}
					else
					{
						try{ boLocation.SaveNew(); }
						catch(Exception ex)
						{ throw new Exception("Error saving new record: CodeTrigger has detected a data exception. Possible duplicate primary key, invalid foreign key reference, or missing fields. Exception details follow below.\r\n\r\n" + ex.Message); }
					}
				}
				foreach(BOLocation boLocation in _boLocationsCachedDelete)
				{
					if((boLocation == null)  || (!boLocation.Id.HasValue))
					continue;
				
					try{ boLocation.Delete(); }
					catch(Exception ex)
					{ throw new Exception("Error deleting record: CodeTrigger has detected a data exception. Possible existing foreign key reference or other error. Exception details follow below.\r\n\r\n" + ex.Message); }
				}
				_boLocationsCachedDelete.Clear();
				
				LoadRecords();
			}
			catch	{	throw;	}
			finally	{	}
		}
		
		public void DeleteRow(object state)
		{
			if(state is BOLocation)
			{
				_boLocations.Remove((BOLocation)state);
				_boLocationsCachedDelete.Add((BOLocation)state);
			}
		}
		#endregion
		
		#region properties
		public BOLocation Filter
		{
			get {	return _searchBO;	}
		}
		public ObservableCollection<BOLocation> Results
		{
			get {	return _boLocations;	}
		}
		
		public string DisplayName
		{
			get {	return _displayName;	}
			set {	_displayName = value;	}
		}
		
		public RelayCommand DeleteRowCommand
		{
			get
			{
				if(_deleteRowCommand == null)
					_deleteRowCommand = new RelayCommand(DeleteRow);
				return _deleteRowCommand;
			}
		}
		#endregion
	}
}

