/*************************************************************
** Class generated by CodeTrigger, Version 6.3.0.4
** This class was generated on 2020-08-01 3:54:27 AM
** Changes to this file may cause incorrect behaviour and will be lost if the code is regenerated
**************************************************************/
using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using AAF.BusinessObjects;
using Expr = AAF.BusinessObjects;

namespace AAF.MVVMSample.ViewModel
{
	public partial class MenuViewModel : IViewModelBase
	{
		/*WARNING - This class was generated by CodeTrigger. Changes to this file may cause incorrect behaviour and will be lost when the code is regenerated*/
		#region members
		private string _displayName = "Menu";
		private readonly BOMenu _searchBO = new BOMenu();
		private readonly ObservableCollection<BOMenu> _boMenus = new ObservableCollection<BOMenu>();
		private IList<BOMenu> _boMenusCached = new List<BOMenu>();
		private IList<BOMenu> _boMenusCachedDelete = new List<BOMenu>();
		private RelayCommand _deleteRowCommand;
		#endregion
		
		#region constructor
		public MenuViewModel()
		{		}
		#endregion
		
		#region methods
		public static IList<BOMenu> GetMenuList()
		{
			try
			{
				IList<BOMenu> listMenu = BOMenu.MenuCollection();
				return listMenu;
			}
			catch(Exception)
			{	/*rethrow or handle gracefully*/return null;	}
			finally	{	}
		}
		
		private void AddExpr(ref Criteria<BOMenu> crit, string propertyName, object propertyValue, string propertyValueText, Func<object, string> formatter = null)
		{
			bool wildcard = propertyValueText.Contains("%");
			crit.Add(wildcard
				? Expression.Like(propertyName, propertyValue, formatter)
				: Expression.Eq(propertyName, propertyValue, formatter));
		}

		public int GetLoadCount()
		{
			var crit = new Criteria<BOMenu>();
			try
			{
				if(_searchBO.Id.HasValue) AddExpr(ref crit, "Id", _searchBO.Id, "" );
				if(_searchBO.RestaurantMenuId.HasValue) AddExpr(ref crit, "RestaurantMenuId", _searchBO.RestaurantMenuId, "" );
				if(_searchBO.Price.HasValue) AddExpr(ref crit, "Price", _searchBO.Price, "" );
				if(_searchBO.UseItemDescription.HasValue) AddExpr(ref crit, "UseItemDescription", _searchBO.UseItemDescription, "" );
				if(_searchBO.StateId.HasValue) AddExpr(ref crit, "StateId", _searchBO.StateId, "" );
				if(_searchBO.NameKey.HasValue) AddExpr(ref crit, "NameKey", _searchBO.NameKey, "" );
				if(_searchBO.DescriptionKey.HasValue) AddExpr(ref crit, "DescriptionKey", _searchBO.DescriptionKey, "" );
				int resultCount = crit.Count();
				return resultCount;
			}
			catch	{	throw;	}
			finally	{	}
		}
		
		public void LoadRecords()
		{
			var crit = new Criteria<BOMenu>();
			try
			{
				if(_searchBO.Id.HasValue) AddExpr(ref crit, "Id", _searchBO.Id, "" );
				if(_searchBO.RestaurantMenuId.HasValue) AddExpr(ref crit, "RestaurantMenuId", _searchBO.RestaurantMenuId, "" );
				if(_searchBO.Price.HasValue) AddExpr(ref crit, "Price", _searchBO.Price, "" );
				if(_searchBO.UseItemDescription.HasValue) AddExpr(ref crit, "UseItemDescription", _searchBO.UseItemDescription, "" );
				if(_searchBO.StateId.HasValue) AddExpr(ref crit, "StateId", _searchBO.StateId, "" );
				if(_searchBO.NameKey.HasValue) AddExpr(ref crit, "NameKey", _searchBO.NameKey, "" );
				if(_searchBO.DescriptionKey.HasValue) AddExpr(ref crit, "DescriptionKey", _searchBO.DescriptionKey, "" );
				
				_boMenus.Clear();
				_boMenusCachedDelete.Clear();
				_boMenusCached = crit.List<BOMenu>();
				foreach(BOMenu boMenu in _boMenusCached)
					_boMenus.Add(boMenu);
			}
			catch	{	throw;	}
			finally	{	}
		}
		
		public void SaveCurrentView()
		{
			try
			{
				foreach(BOMenu boMenu in _boMenus)
				{
					if(_boMenusCached.Contains(boMenu))
					{
						if(!boMenu.IsDirty) continue;
						try{ boMenu.Update(); }
						catch(Exception ex)
						{ throw new Exception("Error updating record: CodeTrigger has detected a data exception. Possible invalid foreign key reference, missing fields or other error. Exception details follow below.\r\n\r\n" + ex.Message); }
					}
					else
					{
						try{ boMenu.SaveNew(); }
						catch(Exception ex)
						{ throw new Exception("Error saving new record: CodeTrigger has detected a data exception. Possible duplicate primary key, invalid foreign key reference, or missing fields. Exception details follow below.\r\n\r\n" + ex.Message); }
					}
				}
				foreach(BOMenu boMenu in _boMenusCachedDelete)
				{
					if((boMenu == null)  || (!boMenu.Id.HasValue))
					continue;
				
					try{ boMenu.Delete(); }
					catch(Exception ex)
					{ throw new Exception("Error deleting record: CodeTrigger has detected a data exception. Possible existing foreign key reference or other error. Exception details follow below.\r\n\r\n" + ex.Message); }
				}
				_boMenusCachedDelete.Clear();
				
				LoadRecords();
			}
			catch	{	throw;	}
			finally	{	}
		}
		
		public void DeleteRow(object state)
		{
			if(state is BOMenu)
			{
				_boMenus.Remove((BOMenu)state);
				_boMenusCachedDelete.Add((BOMenu)state);
			}
		}
		#endregion
		
		#region properties
		public BOMenu Filter
		{
			get {	return _searchBO;	}
		}
		public ObservableCollection<BOMenu> Results
		{
			get {	return _boMenus;	}
		}
		
		public string DisplayName
		{
			get {	return _displayName;	}
			set {	_displayName = value;	}
		}
		
		public RelayCommand DeleteRowCommand
		{
			get
			{
				if(_deleteRowCommand == null)
					_deleteRowCommand = new RelayCommand(DeleteRow);
				return _deleteRowCommand;
			}
		}
		#endregion
	}
}

