/*************************************************************
** Class generated by CodeTrigger, Version 6.3.0.4
** This class was generated on 2020-08-01 3:54:27 AM
** Changes to this file may cause incorrect behaviour and will be lost if the code is regenerated
**************************************************************/
using System;
using System.Collections.Generic;
using System.Windows.Input;
namespace AAF.MVVMSample.ViewModel
{
	public partial class MenuItem
	{
		public string Text { get; set; }
		public List<MenuItem> Children { get; private set; }
		public ICommand Command { get; set; }
		public MenuItem(string text)
		{
			Text = text;
			Children = new List<MenuItem>();
		}
	}
}

