/*************************************************************
** Class generated by CodeTrigger, Version 6.3.0.4
** This class was generated on 2020-08-01 3:54:27 AM
** Changes to this file may cause incorrect behaviour and will be lost if the code is regenerated
**************************************************************/
using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using AAF.BusinessObjects;
using Expr = AAF.BusinessObjects;

namespace AAF.MVVMSample.ViewModel
{
	public partial class StateViewModel : IViewModelBase
	{
		/*WARNING - This class was generated by CodeTrigger. Changes to this file may cause incorrect behaviour and will be lost when the code is regenerated*/
		#region members
		private string _displayName = "State";
		private readonly BOState _searchBO = new BOState();
		private readonly ObservableCollection<BOState> _boStates = new ObservableCollection<BOState>();
		private IList<BOState> _boStatesCached = new List<BOState>();
		private IList<BOState> _boStatesCachedDelete = new List<BOState>();
		private RelayCommand _deleteRowCommand;
		#endregion
		
		#region constructor
		public StateViewModel()
		{		}
		#endregion
		
		#region methods
		public static IList<BOState> GetStateList()
		{
			try
			{
				IList<BOState> listState = BOState.StateCollection();
				return listState;
			}
			catch(Exception)
			{	/*rethrow or handle gracefully*/return null;	}
			finally	{	}
		}
		
		private void AddExpr(ref Criteria<BOState> crit, string propertyName, object propertyValue, string propertyValueText, Func<object, string> formatter = null)
		{
			bool wildcard = propertyValueText.Contains("%");
			crit.Add(wildcard
				? Expression.Like(propertyName, propertyValue, formatter)
				: Expression.Eq(propertyName, propertyValue, formatter));
		}

		public int GetLoadCount()
		{
			var crit = new Criteria<BOState>();
			try
			{
				if(_searchBO.Id.HasValue) AddExpr(ref crit, "Id", _searchBO.Id, "" );
				if(!string.IsNullOrEmpty(_searchBO.Name)) AddExpr(ref crit, "Name", _searchBO.Name, _searchBO.Name);
				int resultCount = crit.Count();
				return resultCount;
			}
			catch	{	throw;	}
			finally	{	}
		}
		
		public void LoadRecords()
		{
			var crit = new Criteria<BOState>();
			try
			{
				if(_searchBO.Id.HasValue) AddExpr(ref crit, "Id", _searchBO.Id, "" );
				if(!string.IsNullOrEmpty(_searchBO.Name)) AddExpr(ref crit, "Name", _searchBO.Name, _searchBO.Name);
				
				_boStates.Clear();
				_boStatesCachedDelete.Clear();
				_boStatesCached = crit.List<BOState>();
				foreach(BOState boState in _boStatesCached)
					_boStates.Add(boState);
			}
			catch	{	throw;	}
			finally	{	}
		}
		
		public void SaveCurrentView()
		{
			try
			{
				foreach(BOState boState in _boStates)
				{
					if(_boStatesCached.Contains(boState))
					{
						if(!boState.IsDirty) continue;
						try{ boState.Update(); }
						catch(Exception ex)
						{ throw new Exception("Error updating record: CodeTrigger has detected a data exception. Possible invalid foreign key reference, missing fields or other error. Exception details follow below.\r\n\r\n" + ex.Message); }
					}
					else
					{
						try{ boState.SaveNew(); }
						catch(Exception ex)
						{ throw new Exception("Error saving new record: CodeTrigger has detected a data exception. Possible duplicate primary key, invalid foreign key reference, or missing fields. Exception details follow below.\r\n\r\n" + ex.Message); }
					}
				}
				foreach(BOState boState in _boStatesCachedDelete)
				{
					if((boState == null)  || (!boState.Id.HasValue))
					continue;
				
					try{ boState.Delete(); }
					catch(Exception ex)
					{ throw new Exception("Error deleting record: CodeTrigger has detected a data exception. Possible existing foreign key reference or other error. Exception details follow below.\r\n\r\n" + ex.Message); }
				}
				_boStatesCachedDelete.Clear();
				
				LoadRecords();
			}
			catch	{	throw;	}
			finally	{	}
		}
		
		public void DeleteRow(object state)
		{
			if(state is BOState)
			{
				_boStates.Remove((BOState)state);
				_boStatesCachedDelete.Add((BOState)state);
			}
		}
		#endregion
		
		#region properties
		public BOState Filter
		{
			get {	return _searchBO;	}
		}
		public ObservableCollection<BOState> Results
		{
			get {	return _boStates;	}
		}
		
		public string DisplayName
		{
			get {	return _displayName;	}
			set {	_displayName = value;	}
		}
		
		public RelayCommand DeleteRowCommand
		{
			get
			{
				if(_deleteRowCommand == null)
					_deleteRowCommand = new RelayCommand(DeleteRow);
				return _deleteRowCommand;
			}
		}
		#endregion
	}
}

