/*************************************************************
** Class generated by CodeTrigger, Version 6.3.0.4
** This class was generated on 2020-08-01 3:54:27 AM
** Changes to this file may cause incorrect behaviour and will be lost if the code is regenerated
**************************************************************/
using System;
using System.Data;
using System.Data.SqlClient;
using System.Collections.Generic;
using AAF.DataObjects.Interfaces;

namespace AAF.DataObjects
{
	public partial class DAOKey : zAAFConn_BaseData
	{
		#region member variables
		protected Int32? _key;
		protected byte? _type;
		protected Int32? _rootId;
		protected Int32? _objectId;
		protected Int32? _id;
		protected string _keyName;
		protected string _code;
		protected Int32? _errorCode;
		#endregion

		#region class methods
		public DAOKey()
		{
		}
		///<Summary>
		///Select one row by primary key(s)
		///This method returns one row from the table Key based on the primary key(s)
		///</Summary>
		///<returns>
		///DAOKey
		///</returns>
		///<parameters>
		///Int32? key
		///</parameters>
		public static DAOKey SelectOne(Int32? key)
		{
			SqlCommand	command = new SqlCommand();
			command.CommandText = InlineProcs.ctprKey_SelectOne;
			command.CommandType = CommandType.Text;
			SqlConnection staticConnection = StaticSqlConnection;
			command.Connection = staticConnection;

			DataTable dt = new DataTable("Key");
			SqlDataAdapter sqlAdapter = new SqlDataAdapter(command);
			try
			{
				command.Parameters.Add(CtSqlParameter.Get("@Key", SqlDbType.Int, 4, ParameterDirection.Input, false, 10, 0, "", DataRowVersion.Proposed, (object)key?? (object)DBNull.Value));
				command.Parameters.Add(CtSqlParameter.Get("@ErrorCode", SqlDbType.Int, 4, ParameterDirection.Output, false, 10, 0, "", DataRowVersion.Proposed, null));

				staticConnection.Open();
				sqlAdapter.Fill(dt);

				int errorCode = (Int32)command.Parameters["@ErrorCode"].Value;
				if(errorCode > 1)
					throw new Exception("procedure ctprKey_SelectOne returned error code: " + errorCode );

				DAOKey retObj = null;
				if(dt.Rows.Count > 0)
				{
					retObj = new DAOKey();
					retObj._key					 = Convert.IsDBNull(dt.Rows[0]["Key"]) ? (Int32?)null : (Int32?)dt.Rows[0]["Key"];
					retObj._type					 = Convert.IsDBNull(dt.Rows[0]["Type"]) ? (byte?)null : (byte?)dt.Rows[0]["Type"];
					retObj._rootId					 = Convert.IsDBNull(dt.Rows[0]["RootId"]) ? (Int32?)null : (Int32?)dt.Rows[0]["RootId"];
					retObj._objectId					 = Convert.IsDBNull(dt.Rows[0]["Object_id"]) ? (Int32?)null : (Int32?)dt.Rows[0]["Object_id"];
					retObj._id					 = Convert.IsDBNull(dt.Rows[0]["Id"]) ? (Int32?)null : (Int32?)dt.Rows[0]["Id"];
					retObj._keyName					 = Convert.IsDBNull(dt.Rows[0]["KeyName"]) ? null : (string)dt.Rows[0]["KeyName"];
					retObj._code					 = Convert.IsDBNull(dt.Rows[0]["Code"]) ? null : (string)dt.Rows[0]["Code"];
				}
				return retObj;
			}
			catch(Exception ex)
			{
				Handle(null, ex);
				return null;
			}
			finally
			{
				staticConnection.Close();
				command.Dispose();
			}
		}

		///<Summary>
		///Delete one row by primary key(s)
		///this method allows the object to delete itself from the table Key based on its primary key
		///</Summary>
		///<returns>
		///void
		///</returns>
		///<parameters>
		///
		///</parameters>
		public virtual void Delete()
		{
			SqlCommand	command = new SqlCommand();
			command.CommandText = InlineProcs.ctprKey_DeleteOne;
			command.CommandType = CommandType.Text;
			command.Connection = _connectionProvider.Connection;
			command.Transaction = _connectionProvider.CurrentTransaction;

			try
			{
				command.Parameters.Add(CtSqlParameter.Get("@Key", SqlDbType.Int, 4, ParameterDirection.Input, false, 10, 0, "", DataRowVersion.Proposed, (object)_key?? (object)DBNull.Value));
				command.Parameters.Add(CtSqlParameter.Get("@ErrorCode", SqlDbType.Int, 4, ParameterDirection.Output, false, 10, 0, "", DataRowVersion.Proposed, _errorCode));

				command.ExecuteNonQuery();

				_errorCode = (Int32)command.Parameters["@ErrorCode"].Value;
				if(_errorCode > 1)
					throw new Exception("procedure ctprKey_DeleteOne returned error code: " + _errorCode );

			}
			catch(Exception ex)
			{
				Handle(this, ex);
			}
			finally
			{
				command.Dispose();
			}
		}

		///<Summary>
		///Select one row by unique constraint
		///This method returns one row from the table Key based on a unique constraint
		///</Summary>
		///<returns>
		///DAOKey
		///</returns>
		///<parameters>
		///string code
		///</parameters>
		public static DAOKey SelectOneByCode(string code)
		{
			SqlCommand	command = new SqlCommand();
			command.CommandText = InlineProcs.ctprKey_SelectOneByCode;
			command.CommandType = CommandType.Text;
			SqlConnection staticConnection = StaticSqlConnection;
			command.Connection = staticConnection;

			DataTable dt = new DataTable("Key");
			SqlDataAdapter sqlAdapter = new SqlDataAdapter(command);
			try
			{
				command.Parameters.Add(CtSqlParameter.Get("@Code", SqlDbType.VarChar, 50, ParameterDirection.Input, false, 0, 0, "", DataRowVersion.Proposed, (object)code?? (object)DBNull.Value));
				command.Parameters.Add(CtSqlParameter.Get("@ErrorCode", SqlDbType.Int, 4, ParameterDirection.Output, false, 10, 0, "", DataRowVersion.Proposed, null));

				staticConnection.Open();
				sqlAdapter.Fill(dt);

				int errorCode = (Int32)command.Parameters["@ErrorCode"].Value;
				if(errorCode > 1)
					throw new Exception("procedure ctprKey_SelectOneByCode returned error code: " + errorCode );

				DAOKey retObj = null;
				if(dt.Rows.Count > 0)
				{
					retObj = new DAOKey();
					retObj._key					 = Convert.IsDBNull(dt.Rows[0]["Key"]) ? (Int32?)null : (Int32?)dt.Rows[0]["Key"];
					retObj._type					 = Convert.IsDBNull(dt.Rows[0]["Type"]) ? (byte?)null : (byte?)dt.Rows[0]["Type"];
					retObj._rootId					 = Convert.IsDBNull(dt.Rows[0]["RootId"]) ? (Int32?)null : (Int32?)dt.Rows[0]["RootId"];
					retObj._objectId					 = Convert.IsDBNull(dt.Rows[0]["Object_id"]) ? (Int32?)null : (Int32?)dt.Rows[0]["Object_id"];
					retObj._id					 = Convert.IsDBNull(dt.Rows[0]["Id"]) ? (Int32?)null : (Int32?)dt.Rows[0]["Id"];
					retObj._keyName					 = Convert.IsDBNull(dt.Rows[0]["KeyName"]) ? null : (string)dt.Rows[0]["KeyName"];
					retObj._code					 = Convert.IsDBNull(dt.Rows[0]["Code"]) ? null : (string)dt.Rows[0]["Code"];
				}
				return retObj;
			}
			catch(Exception ex)
			{
				Handle(null, ex);
				return null;
			}
			finally
			{
				staticConnection.Close();
				command.Dispose();
			}
		}

		///<Summary>
		///Delete one row by unique constraint
		///This method deletes one row from the table Key based on a unique constraint
		///</Summary>
		///<returns>
		///void
		///</returns>
		///<parameters>
		///string code
		///</parameters>
		public virtual void DeleteOneByCode(string code)
		{
			SqlCommand	command = new SqlCommand();
			command.CommandText = InlineProcs.ctprKey_DeleteOneByCode;
			command.CommandType = CommandType.Text;
			command.Connection = _connectionProvider.Connection;
			command.Transaction = _connectionProvider.CurrentTransaction;

			try
			{
				command.Parameters.Add(CtSqlParameter.Get("@Code", SqlDbType.VarChar, 50, ParameterDirection.Input, false, 0, 0, "", DataRowVersion.Proposed, (object)_code?? (object)DBNull.Value));
				command.Parameters.Add(CtSqlParameter.Get("@ErrorCode", SqlDbType.Int, 4, ParameterDirection.Output, false, 10, 0, "", DataRowVersion.Proposed, _errorCode));

				command.ExecuteNonQuery();

				_errorCode = (Int32)command.Parameters["@ErrorCode"].Value;
				if(_errorCode > 1)
					throw new Exception("procedure ctprKey_DeleteOneByCode returned error code: " + _errorCode );

			}
			catch(Exception ex)
			{
				Handle(this, ex);
			}
			finally
			{
				command.Dispose();
			}
		}

		///<Summary>
		///Insert a new row
		///This method saves a new object to the table Key
		///</Summary>
		///<returns>
		///void
		///</returns>
		///<parameters>
		///
		///</parameters>
		public virtual void Insert()
		{
			SqlCommand	command = new SqlCommand();
			command.CommandText = InlineProcs.ctprKey_InsertOne;
			command.CommandType = CommandType.Text;
			command.Connection = _connectionProvider.Connection;
			command.Transaction = _connectionProvider.CurrentTransaction;

			try
			{
				command.Parameters.Add(CtSqlParameter.Get("@Key", SqlDbType.Int, 4, ParameterDirection.Output, false, 10, 0, "", DataRowVersion.Proposed, _key));
				command.Parameters.Add(CtSqlParameter.Get("@Type", SqlDbType.TinyInt, 1, ParameterDirection.InputOutput, false, 3, 0, "", DataRowVersion.Proposed, (object)_type?? (object)DBNull.Value));
				command.Parameters.Add(CtSqlParameter.Get("@RootId", SqlDbType.Int, 4, ParameterDirection.InputOutput, false, 10, 0, "", DataRowVersion.Proposed, (object)_rootId?? (object)DBNull.Value));
				command.Parameters.Add(CtSqlParameter.Get("@Object_id", SqlDbType.Int, 4, ParameterDirection.InputOutput, false, 10, 0, "", DataRowVersion.Proposed, (object)_objectId?? (object)DBNull.Value));
				command.Parameters.Add(CtSqlParameter.Get("@Id", SqlDbType.Int, 4, ParameterDirection.InputOutput, false, 10, 0, "", DataRowVersion.Proposed, (object)_id?? (object)DBNull.Value));
				command.Parameters.Add(CtSqlParameter.Get("@KeyName", SqlDbType.VarChar, 50, ParameterDirection.InputOutput, false, 0, 0, "", DataRowVersion.Proposed, (object)_keyName?? (object)DBNull.Value));
				command.Parameters.Add(CtSqlParameter.Get("@Code", SqlDbType.VarChar, 50, ParameterDirection.InputOutput, false, 0, 0, "", DataRowVersion.Proposed, (object)_code?? (object)DBNull.Value));
				command.Parameters.Add(CtSqlParameter.Get("@ErrorCode", SqlDbType.Int, 4, ParameterDirection.Output, false, 10, 0, "", DataRowVersion.Proposed, _errorCode));

				command.ExecuteNonQuery();

				_errorCode = (Int32)command.Parameters["@ErrorCode"].Value;
				if(_errorCode > 1)
					throw new Exception("procedure ctprKey_InsertOne returned error code: " + _errorCode );

				_key					 = Convert.IsDBNull(command.Parameters["@Key"].Value) ? (Int32?)null : (Int32?)command.Parameters["@Key"].Value;
				_type					 = Convert.IsDBNull(command.Parameters["@Type"].Value) ? (byte?)null : (byte?)command.Parameters["@Type"].Value;
				_rootId					 = Convert.IsDBNull(command.Parameters["@RootId"].Value) ? (Int32?)null : (Int32?)command.Parameters["@RootId"].Value;
				_objectId					 = Convert.IsDBNull(command.Parameters["@Object_id"].Value) ? (Int32?)null : (Int32?)command.Parameters["@Object_id"].Value;
				_id					 = Convert.IsDBNull(command.Parameters["@Id"].Value) ? (Int32?)null : (Int32?)command.Parameters["@Id"].Value;
				_keyName					 = Convert.IsDBNull(command.Parameters["@KeyName"].Value) ? null : (string)command.Parameters["@KeyName"].Value;
				_code					 = Convert.IsDBNull(command.Parameters["@Code"].Value) ? null : (string)command.Parameters["@Code"].Value;

			}
			catch(Exception ex)
			{
				Handle(this, ex);
			}
			finally
			{
				command.Dispose();
			}
		}

		///<Summary>
		///Select all rows
		///This method returns all data rows in the table Key
		///</Summary>
		///<returns>
		///IList-DAOKey.
		///</returns>
		///<parameters>
		///
		///</parameters>
		public static IList<DAOKey> SelectAll()
		{
			SqlCommand	command = new SqlCommand();
			command.CommandText = InlineProcs.ctprKey_SelectAll;
			command.CommandType = CommandType.Text;
			SqlConnection staticConnection = StaticSqlConnection;
			command.Connection = staticConnection;

			DataTable dt = new DataTable("Key");
			SqlDataAdapter sqlAdapter = new SqlDataAdapter(command);
			try
			{
				command.Parameters.Add(CtSqlParameter.Get("@ErrorCode", SqlDbType.Int, 4, ParameterDirection.Output, false, 10, 0, "", DataRowVersion.Proposed, null));

				staticConnection.Open();
				sqlAdapter.Fill(dt);

				int errorCode = (Int32)command.Parameters["@ErrorCode"].Value;
				if(errorCode > 1)
					throw new Exception("procedure ctprKey_SelectAll returned error code: " + errorCode );

				List<DAOKey> objList = new List<DAOKey>();
				if(dt.Rows.Count > 0)
				{
					foreach(DataRow row in dt.Rows)
					{
						DAOKey retObj = new DAOKey();
						retObj._key					 = Convert.IsDBNull(row["Key"]) ? (Int32?)null : (Int32?)row["Key"];
						retObj._type					 = Convert.IsDBNull(row["Type"]) ? (byte?)null : (byte?)row["Type"];
						retObj._rootId					 = Convert.IsDBNull(row["RootId"]) ? (Int32?)null : (Int32?)row["RootId"];
						retObj._objectId					 = Convert.IsDBNull(row["Object_id"]) ? (Int32?)null : (Int32?)row["Object_id"];
						retObj._id					 = Convert.IsDBNull(row["Id"]) ? (Int32?)null : (Int32?)row["Id"];
						retObj._keyName					 = Convert.IsDBNull(row["KeyName"]) ? null : (string)row["KeyName"];
						retObj._code					 = Convert.IsDBNull(row["Code"]) ? null : (string)row["Code"];
						objList.Add(retObj);
					}
				}
				return objList;
			}
			catch(Exception ex)
			{
				Handle(null, ex);
				return null;
			}
			finally
			{
				staticConnection.Close();
				command.Dispose();
			}
		}

		///<Summary>
		///</Summary>
		///<returns>
		///Int32
		///</returns>
		///<parameters>
		///
		///</parameters>
		public static Int32 SelectAllCount()
		{
			SqlCommand	command = new SqlCommand();
			command.CommandText = InlineProcs.ctprKey_SelectAllCount;
			command.CommandType = CommandType.Text;
			SqlConnection staticConnection = StaticSqlConnection;
			command.Connection = staticConnection;

			try
			{
				command.Parameters.Add(CtSqlParameter.Get("@ErrorCode", SqlDbType.Int, 4, ParameterDirection.Output, false, 10, 0, "", DataRowVersion.Proposed, null));

				staticConnection.Open();
				Int32 retCount = (Int32)command.ExecuteScalar();

				int errorCode = (Int32)command.Parameters["@ErrorCode"].Value;
				if(errorCode > 1)
					throw new Exception("procedure ctprKey_SelectAllCount returned error code: " + errorCode );

				return retCount;
			}
			catch(Exception ex)
			{
				Handle(null, ex);
				return -1;
			}
			finally
			{
				staticConnection.Close();
				command.Dispose();
			}
		}

		///<Summary>
		///Select specific fields of all rows using criteriaquery api
		///This method returns specific fields of all data rows in the table using criteriaquery apiKey
		///</Summary>
		///<returns>
		///IDictionary-string, IList-object..
		///</returns>
		///<parameters>
		///IList<IDataProjection> listProjection, IList<IDataCriterion> listCriterion, IList<IDataOrderBy> listOrder, IDataSkip dataSkip, IDataTake dataTake
		///</parameters>
		public static IDictionary<string, IList<object>> SelectAllByCriteriaProjection(IList<IDataProjection> listProjection, IList<IDataCriterion> listCriterion, IList<IDataOrderBy> listOrder, IDataSkip dataSkip, IDataTake dataTake)
		{
			SqlCommand	command = new SqlCommand();
			command.CommandText = GetSelectionCriteria(InlineProcs.ctprKey_SelectAllByCriteriaProjection, listProjection, listCriterion, listOrder, dataSkip, dataTake);
			command.CommandType = CommandType.Text;
			SqlConnection staticConnection = StaticSqlConnection;
			command.Connection = staticConnection;

			DataTable dt = new DataTable("Key");
			SqlDataAdapter sqlAdapter = new SqlDataAdapter(command);
			try
			{
				command.Parameters.Add(CtSqlParameter.Get("@ErrorCode", SqlDbType.Int, 4, ParameterDirection.Output, false, 10, 0, "", DataRowVersion.Proposed, null));

				staticConnection.Open();
				sqlAdapter.Fill(dt);

				int errorCode = (Int32)command.Parameters["@ErrorCode"].Value;
				if(errorCode > 1)
					throw new Exception("procedure ctprKey_SelectAllByCriteriaProjection returned error code: " + errorCode );

				IDictionary<string, IList<object>> dict = new Dictionary<string, IList<object>>();
				foreach (IDataProjection projection in listProjection)
				{
					IList<object> lst = new List<object>();
					dict.Add(projection.Member, lst);
					foreach (DataRow row in dt.Rows)
					{
						if (string.Compare(projection.Member, "Key", true) == 0) lst.Add(Convert.IsDBNull(row["Key"]) ? (Int32?)null : (Int32?)row["Key"]);
						if (string.Compare(projection.Member, "Type", true) == 0) lst.Add(Convert.IsDBNull(row["Type"]) ? (byte?)null : (byte?)row["Type"]);
						if (string.Compare(projection.Member, "RootId", true) == 0) lst.Add(Convert.IsDBNull(row["RootId"]) ? (Int32?)null : (Int32?)row["RootId"]);
						if (string.Compare(projection.Member, "Object_id", true) == 0) lst.Add(Convert.IsDBNull(row["Object_id"]) ? (Int32?)null : (Int32?)row["Object_id"]);
						if (string.Compare(projection.Member, "Id", true) == 0) lst.Add(Convert.IsDBNull(row["Id"]) ? (Int32?)null : (Int32?)row["Id"]);
						if (string.Compare(projection.Member, "KeyName", true) == 0) lst.Add(Convert.IsDBNull(row["KeyName"]) ? null : (string)row["KeyName"]);
						if (string.Compare(projection.Member, "Code", true) == 0) lst.Add(Convert.IsDBNull(row["Code"]) ? null : (string)row["Code"]);
					}
				}
				return dict;
			}
			catch(Exception ex)
			{
				Handle(null, ex);
				return null;
			}
			finally
			{
				staticConnection.Close();
				command.Dispose();
			}
		}

		///<Summary>
		///Select all rows by filter criteria
		///This method returns all data rows in the table using criteriaquery api Key
		///</Summary>
		///<returns>
		///IList-DAOKey.
		///</returns>
		///<parameters>
		///IList<IDataCriterion> listCriterion, IList<IDataOrderBy> listOrder, IDataSkip dataSkip, IDataTake dataTake
		///</parameters>
		public static IList<DAOKey> SelectAllByCriteria(IList<IDataCriterion> listCriterion, IList<IDataOrderBy> listOrder, IDataSkip dataSkip, IDataTake dataTake)
		{
			SqlCommand	command = new SqlCommand();
			command.CommandText = GetSelectionCriteria(InlineProcs.ctprKey_SelectAllByCriteria, null, listCriterion, listOrder, dataSkip, dataTake);
			command.CommandType = CommandType.Text;
			SqlConnection staticConnection = StaticSqlConnection;
			command.Connection = staticConnection;

			DataTable dt = new DataTable("Key");
			SqlDataAdapter sqlAdapter = new SqlDataAdapter(command);
			try
			{
				command.Parameters.Add(CtSqlParameter.Get("@ErrorCode", SqlDbType.Int, 4, ParameterDirection.Output, false, 10, 0, "", DataRowVersion.Proposed, null));

				staticConnection.Open();
				sqlAdapter.Fill(dt);

				int errorCode = (Int32)command.Parameters["@ErrorCode"].Value;
				if(errorCode > 1)
					throw new Exception("procedure ctprKey_SelectAllByCriteria returned error code: " + errorCode );

				List<DAOKey> objList = new List<DAOKey>();
				if(dt.Rows.Count > 0)
				{
					foreach(DataRow row in dt.Rows)
					{
						DAOKey retObj = new DAOKey();
						retObj._key					 = Convert.IsDBNull(row["Key"]) ? (Int32?)null : (Int32?)row["Key"];
						retObj._type					 = Convert.IsDBNull(row["Type"]) ? (byte?)null : (byte?)row["Type"];
						retObj._rootId					 = Convert.IsDBNull(row["RootId"]) ? (Int32?)null : (Int32?)row["RootId"];
						retObj._objectId					 = Convert.IsDBNull(row["Object_id"]) ? (Int32?)null : (Int32?)row["Object_id"];
						retObj._id					 = Convert.IsDBNull(row["Id"]) ? (Int32?)null : (Int32?)row["Id"];
						retObj._keyName					 = Convert.IsDBNull(row["KeyName"]) ? null : (string)row["KeyName"];
						retObj._code					 = Convert.IsDBNull(row["Code"]) ? null : (string)row["Code"];
						objList.Add(retObj);
					}
				}
				return objList;
			}
			catch(Exception ex)
			{
				Handle(null, ex);
				return null;
			}
			finally
			{
				staticConnection.Close();
				command.Dispose();
			}
		}

		///<Summary>
		///Select count of all rows using criteriaquery api
		///This method returns all data rows in the table using criteriaquery api Key
		///</Summary>
		///<returns>
		///Int32
		///</returns>
		///<parameters>
		///IList<IDataCriterion> listCriterion
		///</parameters>
		public static Int32 SelectAllByCriteriaCount(IList<IDataCriterion> listCriterion)
		{
			SqlCommand	command = new SqlCommand();
			command.CommandText = GetSelectionCriteria(InlineProcs.ctprKey_SelectAllByCriteriaCount, null, listCriterion, null);
			command.CommandType = CommandType.Text;
			SqlConnection staticConnection = StaticSqlConnection;
			command.Connection = staticConnection;

			try
			{
				command.Parameters.Add(CtSqlParameter.Get("@ErrorCode", SqlDbType.Int, 4, ParameterDirection.Output, false, 10, 0, "", DataRowVersion.Proposed, null));

				staticConnection.Open();
				Int32 retCount = (Int32)command.ExecuteScalar();

				int errorCode = (Int32)command.Parameters["@ErrorCode"].Value;
				if(errorCode > 1)
					throw new Exception("procedure ctprKey_SelectAllByCriteriaCount returned error code: " + errorCode );

				return retCount;
			}
			catch(Exception ex)
			{
				Handle(null, ex);
				return -1;
			}
			finally
			{
				staticConnection.Close();
				command.Dispose();
			}
		}

		///<Summary>
		///Update one row by primary key(s)
		///This method allows the object to update itself in the table Key based on its primary key(s)
		///</Summary>
		///<returns>
		///void
		///</returns>
		///<parameters>
		///
		///</parameters>
		public virtual void Update()
		{
			SqlCommand	command = new SqlCommand();
			command.CommandText = InlineProcs.ctprKey_UpdateOne;
			command.CommandType = CommandType.Text;
			command.Connection = _connectionProvider.Connection;
			command.Transaction = _connectionProvider.CurrentTransaction;

			try
			{
				command.Parameters.Add(CtSqlParameter.Get("@Key", SqlDbType.Int, 4, ParameterDirection.InputOutput, false, 10, 0, "", DataRowVersion.Proposed, (object)_key?? (object)DBNull.Value));
				command.Parameters.Add(CtSqlParameter.Get("@Type", SqlDbType.TinyInt, 1, ParameterDirection.InputOutput, false, 3, 0, "", DataRowVersion.Proposed, (object)_type?? (object)DBNull.Value));
				command.Parameters.Add(CtSqlParameter.Get("@RootId", SqlDbType.Int, 4, ParameterDirection.InputOutput, false, 10, 0, "", DataRowVersion.Proposed, (object)_rootId?? (object)DBNull.Value));
				command.Parameters.Add(CtSqlParameter.Get("@Object_id", SqlDbType.Int, 4, ParameterDirection.InputOutput, false, 10, 0, "", DataRowVersion.Proposed, (object)_objectId?? (object)DBNull.Value));
				command.Parameters.Add(CtSqlParameter.Get("@Id", SqlDbType.Int, 4, ParameterDirection.InputOutput, false, 10, 0, "", DataRowVersion.Proposed, (object)_id?? (object)DBNull.Value));
				command.Parameters.Add(CtSqlParameter.Get("@KeyName", SqlDbType.VarChar, 50, ParameterDirection.InputOutput, false, 0, 0, "", DataRowVersion.Proposed, (object)_keyName?? (object)DBNull.Value));
				command.Parameters.Add(CtSqlParameter.Get("@Code", SqlDbType.VarChar, 50, ParameterDirection.InputOutput, false, 0, 0, "", DataRowVersion.Proposed, (object)_code?? (object)DBNull.Value));
				command.Parameters.Add(CtSqlParameter.Get("@ErrorCode", SqlDbType.Int, 4, ParameterDirection.Output, false, 10, 0, "", DataRowVersion.Proposed, _errorCode));

				command.ExecuteNonQuery();

				_errorCode = (Int32)command.Parameters["@ErrorCode"].Value;
				if(_errorCode > 1)
					throw new Exception("procedure ctprKey_UpdateOne returned error code: " + _errorCode );

				_key					 = Convert.IsDBNull(command.Parameters["@Key"].Value) ? (Int32?)null : (Int32?)command.Parameters["@Key"].Value;
				_type					 = Convert.IsDBNull(command.Parameters["@Type"].Value) ? (byte?)null : (byte?)command.Parameters["@Type"].Value;
				_rootId					 = Convert.IsDBNull(command.Parameters["@RootId"].Value) ? (Int32?)null : (Int32?)command.Parameters["@RootId"].Value;
				_objectId					 = Convert.IsDBNull(command.Parameters["@Object_id"].Value) ? (Int32?)null : (Int32?)command.Parameters["@Object_id"].Value;
				_id					 = Convert.IsDBNull(command.Parameters["@Id"].Value) ? (Int32?)null : (Int32?)command.Parameters["@Id"].Value;
				_keyName					 = Convert.IsDBNull(command.Parameters["@KeyName"].Value) ? null : (string)command.Parameters["@KeyName"].Value;
				_code					 = Convert.IsDBNull(command.Parameters["@Code"].Value) ? null : (string)command.Parameters["@Code"].Value;

			}
			catch(Exception ex)
			{
				Handle(this, ex);
			}
			finally
			{
				command.Dispose();
			}
		}

		#endregion

		#region member properties

		public Int32? Key
		{
			get
			{
				return _key;
			}
			set
			{
				_key = value;
			}
		}

		public byte? Type
		{
			get
			{
				return _type;
			}
			set
			{
				_type = value;
			}
		}

		public Int32? RootId
		{
			get
			{
				return _rootId;
			}
			set
			{
				_rootId = value;
			}
		}

		public Int32? ObjectId
		{
			get
			{
				return _objectId;
			}
			set
			{
				_objectId = value;
			}
		}

		public Int32? Id
		{
			get
			{
				return _id;
			}
			set
			{
				_id = value;
			}
		}

		public string KeyName
		{
			get
			{
				return _keyName;
			}
			set
			{
				_keyName = value;
			}
		}

		public string Code
		{
			get
			{
				return _code;
			}
			set
			{
				_code = value;
			}
		}

		public Int32? ErrorCode
		{
			get
			{
				return _errorCode;
			}
		}

		#endregion
	}
}

#region inline sql procs
namespace AAF.DataObjects
{
	public partial class InlineProcs
	{
		internal static string ctprKey_SelectOne = @"
			-- Select one row based on the primary key(s)
			SET NOCOUNT ON
			-- selects all rows from the table
			-- returning the error code if any
			SELECT 
			[Key]
			,[Type]
			,[RootId]
			,[Object_id]
			,[Id]
			,[KeyName]
			,[Code]
			FROM [administrator].[Key]
			WHERE 
			[Key] = @Key
			-- returning the error code if any
			SELECT @ErrorCode = @@ERROR
			";

		internal static string ctprKey_DeleteOne = @"
			-- Delete a row based on the primary key(s)
			SET NOCOUNT ON
			-- delete all matching from the table
			-- returning the error code if any
			DELETE [administrator].[Key]
			WHERE 
			[Key] = @Key
			-- returning the error code if any
			SELECT @ErrorCode = @@ERROR
			";

		internal static string ctprKey_SelectOneByCode = @"
			-- Select one row by a unique constraint
			SET NOCOUNT ON
			-- selects all rows from the table
			-- returning the error code if any
			SELECT 
			[Key]
			,[Type]
			,[RootId]
			,[Object_id]
			,[Id]
			,[KeyName]
			,[Code]
			FROM [administrator].[Key]
			WHERE 
			[Code] = @Code
			-- returning the error code if any
			SELECT @ErrorCode = @@ERROR
			";

		internal static string ctprKey_DeleteOneByCode = @"
			
			SET NOCOUNT ON
			-- delete all matching from the table
			-- returning the error code if any
			DELETE [administrator].[Key]
			WHERE 
			[Code] = @Code
			-- returning the error code if any
			SELECT @ErrorCode = @@ERROR
			";

		internal static string ctprKey_InsertOne = @"
			-- Insert a new row
			SET NOCOUNT ON
			-- inserts a new row into the table
			-- returning the error code if any, and the identity field, if any
			INSERT [administrator].[Key]
			(
			[Type]
			,[RootId]
			,[Object_id]
			,[Id]
			,[KeyName]
			,[Code]
			)
			VALUES
			(
			@Type
			,@RootId
			,@Object_id
			,@Id
			,@KeyName
			,@Code
			)
			SELECT 
			@Key = [Key]
			,@Type = [Type]
			,@RootId = [RootId]
			,@Object_id = [Object_id]
			,@Id = [Id]
			,@KeyName = [KeyName]
			,@Code = [Code]
			FROM [administrator].[Key]
			WHERE 
			[Key] = SCOPE_IDENTITY()
			-- returning the error code if any
			SELECT @ErrorCode = @@ERROR
			";

		internal static string ctprKey_SelectAll = @"
			-- Select All rows
			SET NOCOUNT ON
			-- selects all rows from the table
			-- returning the error code if any
			SELECT 
			[Key]
			,[Type]
			,[RootId]
			,[Object_id]
			,[Id]
			,[KeyName]
			,[Code]
			FROM [administrator].[Key]
			-- returning the error code if any
			SELECT @ErrorCode = @@ERROR
			";

		internal static string ctprKey_SelectAllCount = @"
			
			SET NOCOUNT ON
			-- selects count of all rows from the table
			-- returning the error code if any
			SELECT COUNT(*)
			FROM [administrator].[Key]
			-- returning the error code if any
			SELECT @ErrorCode = @@ERROR
			";

		internal static string ctprKey_SelectAllByCriteriaProjection = @"
			
			SET NOCOUNT ON
			-- selects all rows from the table by criteria
			-- returning the error code if any
			SELECT 
			##STARTFIELDS##
			##ENDFIELDS##
			FROM [administrator].[Key]
			##CRITERIA##
			-- returning the error code if any
			SELECT @ErrorCode = @@ERROR
			";

		internal static string ctprKey_SelectAllByCriteria = @"
			
			SET NOCOUNT ON
			-- selects all rows from the table by criteria
			-- returning the error code if any
			SELECT 
			[Key]
			,[Type]
			,[RootId]
			,[Object_id]
			,[Id]
			,[KeyName]
			,[Code]
			FROM [administrator].[Key]
			##CRITERIA##
			-- returning the error code if any
			SELECT @ErrorCode = @@ERROR
			";

		internal static string ctprKey_SelectAllByCriteriaCount = @"
			
			SET NOCOUNT ON
			-- selects count of all rows from the table according to criteria
			-- returning the error code if any
			SELECT COUNT(*)
			FROM [administrator].[Key]
			##CRITERIA##
			-- returning the error code if any
			SELECT @ErrorCode = @@ERROR
			";

		internal static string ctprKey_UpdateOne = @"
			-- Update one row based on the primary key(s)
			SET NOCOUNT ON
			-- updates a row in the table based on the primary key
			-- returning the error code if any, and the identity field, if any
			
			UPDATE [administrator].[Key]
			SET
			[Type] = @Type
			,[RootId] = @RootId
			,[Object_id] = @Object_id
			,[Id] = @Id
			,[KeyName] = @KeyName
			,[Code] = @Code
			WHERE 
			[Key] = @Key
			SELECT 
			@Key = [Key]
			,@Type = [Type]
			,@RootId = [RootId]
			,@Object_id = [Object_id]
			,@Id = [Id]
			,@KeyName = [KeyName]
			,@Code = [Code]
			FROM [administrator].[Key]
			WHERE 
			[Key] = @Key
			-- returning the error code if any
			SELECT @ErrorCode = @@ERROR
			";

	}
}
#endregion
