/*************************************************************
** Class generated by CodeTrigger, Version 6.3.0.4
** This class was generated on 2020-08-01 3:54:27 AM
** Changes to this file may cause incorrect behaviour and will be lost if the code is regenerated
**************************************************************/
using System;
using System.Data;
using System.Data.SqlClient;
using System.Collections.Generic;
using AAF.DataObjects.Interfaces;

namespace AAF.DataObjects
{
	public partial class DAOLocation : zAAFConn_BaseData
	{
		#region member variables
		protected Int32? _id;
		protected Int32? _unit;
		protected string _postalCode;
		protected string _streetName;
		protected string _link;
		protected string _map;
		protected string _latLong;
		protected Int32? _errorCode;
		#endregion

		#region class methods
		public DAOLocation()
		{
		}
		///<Summary>
		///Select one row by primary key(s)
		///This method returns one row from the table Location based on the primary key(s)
		///</Summary>
		///<returns>
		///DAOLocation
		///</returns>
		///<parameters>
		///Int32? id
		///</parameters>
		public static DAOLocation SelectOne(Int32? id)
		{
			SqlCommand	command = new SqlCommand();
			command.CommandText = InlineProcs.ctprLocation_SelectOne;
			command.CommandType = CommandType.Text;
			SqlConnection staticConnection = StaticSqlConnection;
			command.Connection = staticConnection;

			DataTable dt = new DataTable("Location");
			SqlDataAdapter sqlAdapter = new SqlDataAdapter(command);
			try
			{
				command.Parameters.Add(CtSqlParameter.Get("@Id", SqlDbType.Int, 4, ParameterDirection.Input, false, 10, 0, "", DataRowVersion.Proposed, (object)id?? (object)DBNull.Value));
				command.Parameters.Add(CtSqlParameter.Get("@ErrorCode", SqlDbType.Int, 4, ParameterDirection.Output, false, 10, 0, "", DataRowVersion.Proposed, null));

				staticConnection.Open();
				sqlAdapter.Fill(dt);

				int errorCode = (Int32)command.Parameters["@ErrorCode"].Value;
				if(errorCode > 1)
					throw new Exception("procedure ctprLocation_SelectOne returned error code: " + errorCode );

				DAOLocation retObj = null;
				if(dt.Rows.Count > 0)
				{
					retObj = new DAOLocation();
					retObj._id					 = Convert.IsDBNull(dt.Rows[0]["Id"]) ? (Int32?)null : (Int32?)dt.Rows[0]["Id"];
					retObj._unit					 = Convert.IsDBNull(dt.Rows[0]["Unit"]) ? (Int32?)null : (Int32?)dt.Rows[0]["Unit"];
					retObj._postalCode					 = Convert.IsDBNull(dt.Rows[0]["PostalCode"]) ? null : (string)dt.Rows[0]["PostalCode"];
					retObj._streetName					 = Convert.IsDBNull(dt.Rows[0]["StreetName"]) ? null : (string)dt.Rows[0]["StreetName"];
					retObj._link					 = Convert.IsDBNull(dt.Rows[0]["Link"]) ? null : (string)dt.Rows[0]["Link"];
					retObj._map					 = Convert.IsDBNull(dt.Rows[0]["Map"]) ? null : (string)dt.Rows[0]["Map"];
					retObj._latLong					 = Convert.IsDBNull(dt.Rows[0]["LatLong"]) ? null : (string)dt.Rows[0]["LatLong"];
				}
				return retObj;
			}
			catch(Exception ex)
			{
				Handle(null, ex);
				return null;
			}
			finally
			{
				staticConnection.Close();
				command.Dispose();
			}
		}

		///<Summary>
		///Delete one row by primary key(s)
		///this method allows the object to delete itself from the table Location based on its primary key
		///</Summary>
		///<returns>
		///void
		///</returns>
		///<parameters>
		///
		///</parameters>
		public virtual void Delete()
		{
			SqlCommand	command = new SqlCommand();
			command.CommandText = InlineProcs.ctprLocation_DeleteOne;
			command.CommandType = CommandType.Text;
			command.Connection = _connectionProvider.Connection;
			command.Transaction = _connectionProvider.CurrentTransaction;

			try
			{
				command.Parameters.Add(CtSqlParameter.Get("@Id", SqlDbType.Int, 4, ParameterDirection.Input, false, 10, 0, "", DataRowVersion.Proposed, (object)_id?? (object)DBNull.Value));
				command.Parameters.Add(CtSqlParameter.Get("@ErrorCode", SqlDbType.Int, 4, ParameterDirection.Output, false, 10, 0, "", DataRowVersion.Proposed, _errorCode));

				command.ExecuteNonQuery();

				_errorCode = (Int32)command.Parameters["@ErrorCode"].Value;
				if(_errorCode > 1)
					throw new Exception("procedure ctprLocation_DeleteOne returned error code: " + _errorCode );

			}
			catch(Exception ex)
			{
				Handle(this, ex);
			}
			finally
			{
				command.Dispose();
			}
		}

		///<Summary>
		///Insert a new row
		///This method saves a new object to the table Location
		///</Summary>
		///<returns>
		///void
		///</returns>
		///<parameters>
		///
		///</parameters>
		public virtual void Insert()
		{
			SqlCommand	command = new SqlCommand();
			command.CommandText = InlineProcs.ctprLocation_InsertOne;
			command.CommandType = CommandType.Text;
			command.Connection = _connectionProvider.Connection;
			command.Transaction = _connectionProvider.CurrentTransaction;

			try
			{
				command.Parameters.Add(CtSqlParameter.Get("@Map", SqlDbType.Text, 2147483647, ParameterDirection.Input, false, 0, 0, "", DataRowVersion.Proposed, (object)_map?? (object)DBNull.Value));
				command.Parameters.Add(CtSqlParameter.Get("@Id", SqlDbType.Int, 4, ParameterDirection.Output, false, 10, 0, "", DataRowVersion.Proposed, _id));
				command.Parameters.Add(CtSqlParameter.Get("@Unit", SqlDbType.Int, 4, ParameterDirection.InputOutput, false, 10, 0, "", DataRowVersion.Proposed, (object)_unit?? (object)DBNull.Value));
				command.Parameters.Add(CtSqlParameter.Get("@PostalCode", SqlDbType.Char, 6, ParameterDirection.InputOutput, false, 0, 0, "", DataRowVersion.Proposed, (object)_postalCode?? (object)DBNull.Value));
				command.Parameters.Add(CtSqlParameter.Get("@StreetName", SqlDbType.NVarChar, 255, ParameterDirection.InputOutput, false, 0, 0, "", DataRowVersion.Proposed, (object)_streetName?? (object)DBNull.Value));
				command.Parameters.Add(CtSqlParameter.Get("@Link", SqlDbType.Char, 17, ParameterDirection.InputOutput, false, 0, 0, "", DataRowVersion.Proposed, (object)_link?? (object)DBNull.Value));
				command.Parameters.Add(CtSqlParameter.Get("@LatLong", SqlDbType.Char, 25, ParameterDirection.InputOutput, false, 0, 0, "", DataRowVersion.Proposed, (object)_latLong?? (object)DBNull.Value));
				command.Parameters.Add(CtSqlParameter.Get("@ErrorCode", SqlDbType.Int, 4, ParameterDirection.Output, false, 10, 0, "", DataRowVersion.Proposed, _errorCode));

				command.ExecuteNonQuery();

				_errorCode = (Int32)command.Parameters["@ErrorCode"].Value;
				if(_errorCode > 1)
					throw new Exception("procedure ctprLocation_InsertOne returned error code: " + _errorCode );

				_id					 = Convert.IsDBNull(command.Parameters["@Id"].Value) ? (Int32?)null : (Int32?)command.Parameters["@Id"].Value;
				_unit					 = Convert.IsDBNull(command.Parameters["@Unit"].Value) ? (Int32?)null : (Int32?)command.Parameters["@Unit"].Value;
				_postalCode					 = Convert.IsDBNull(command.Parameters["@PostalCode"].Value) ? null : (string)command.Parameters["@PostalCode"].Value;
				_streetName					 = Convert.IsDBNull(command.Parameters["@StreetName"].Value) ? null : (string)command.Parameters["@StreetName"].Value;
				_link					 = Convert.IsDBNull(command.Parameters["@Link"].Value) ? null : (string)command.Parameters["@Link"].Value;
				_latLong					 = Convert.IsDBNull(command.Parameters["@LatLong"].Value) ? null : (string)command.Parameters["@LatLong"].Value;

			}
			catch(Exception ex)
			{
				Handle(this, ex);
			}
			finally
			{
				command.Dispose();
			}
		}

		///<Summary>
		///Select all rows
		///This method returns all data rows in the table Location
		///</Summary>
		///<returns>
		///IList-DAOLocation.
		///</returns>
		///<parameters>
		///
		///</parameters>
		public static IList<DAOLocation> SelectAll()
		{
			SqlCommand	command = new SqlCommand();
			command.CommandText = InlineProcs.ctprLocation_SelectAll;
			command.CommandType = CommandType.Text;
			SqlConnection staticConnection = StaticSqlConnection;
			command.Connection = staticConnection;

			DataTable dt = new DataTable("Location");
			SqlDataAdapter sqlAdapter = new SqlDataAdapter(command);
			try
			{
				command.Parameters.Add(CtSqlParameter.Get("@ErrorCode", SqlDbType.Int, 4, ParameterDirection.Output, false, 10, 0, "", DataRowVersion.Proposed, null));

				staticConnection.Open();
				sqlAdapter.Fill(dt);

				int errorCode = (Int32)command.Parameters["@ErrorCode"].Value;
				if(errorCode > 1)
					throw new Exception("procedure ctprLocation_SelectAll returned error code: " + errorCode );

				List<DAOLocation> objList = new List<DAOLocation>();
				if(dt.Rows.Count > 0)
				{
					foreach(DataRow row in dt.Rows)
					{
						DAOLocation retObj = new DAOLocation();
						retObj._id					 = Convert.IsDBNull(row["Id"]) ? (Int32?)null : (Int32?)row["Id"];
						retObj._unit					 = Convert.IsDBNull(row["Unit"]) ? (Int32?)null : (Int32?)row["Unit"];
						retObj._postalCode					 = Convert.IsDBNull(row["PostalCode"]) ? null : (string)row["PostalCode"];
						retObj._streetName					 = Convert.IsDBNull(row["StreetName"]) ? null : (string)row["StreetName"];
						retObj._link					 = Convert.IsDBNull(row["Link"]) ? null : (string)row["Link"];
						retObj._map					 = Convert.IsDBNull(row["Map"]) ? null : (string)row["Map"];
						retObj._latLong					 = Convert.IsDBNull(row["LatLong"]) ? null : (string)row["LatLong"];
						objList.Add(retObj);
					}
				}
				return objList;
			}
			catch(Exception ex)
			{
				Handle(null, ex);
				return null;
			}
			finally
			{
				staticConnection.Close();
				command.Dispose();
			}
		}

		///<Summary>
		///</Summary>
		///<returns>
		///Int32
		///</returns>
		///<parameters>
		///
		///</parameters>
		public static Int32 SelectAllCount()
		{
			SqlCommand	command = new SqlCommand();
			command.CommandText = InlineProcs.ctprLocation_SelectAllCount;
			command.CommandType = CommandType.Text;
			SqlConnection staticConnection = StaticSqlConnection;
			command.Connection = staticConnection;

			try
			{
				command.Parameters.Add(CtSqlParameter.Get("@ErrorCode", SqlDbType.Int, 4, ParameterDirection.Output, false, 10, 0, "", DataRowVersion.Proposed, null));

				staticConnection.Open();
				Int32 retCount = (Int32)command.ExecuteScalar();

				int errorCode = (Int32)command.Parameters["@ErrorCode"].Value;
				if(errorCode > 1)
					throw new Exception("procedure ctprLocation_SelectAllCount returned error code: " + errorCode );

				return retCount;
			}
			catch(Exception ex)
			{
				Handle(null, ex);
				return -1;
			}
			finally
			{
				staticConnection.Close();
				command.Dispose();
			}
		}

		///<Summary>
		///Select specific fields of all rows using criteriaquery api
		///This method returns specific fields of all data rows in the table using criteriaquery apiLocation
		///</Summary>
		///<returns>
		///IDictionary-string, IList-object..
		///</returns>
		///<parameters>
		///IList<IDataProjection> listProjection, IList<IDataCriterion> listCriterion, IList<IDataOrderBy> listOrder, IDataSkip dataSkip, IDataTake dataTake
		///</parameters>
		public static IDictionary<string, IList<object>> SelectAllByCriteriaProjection(IList<IDataProjection> listProjection, IList<IDataCriterion> listCriterion, IList<IDataOrderBy> listOrder, IDataSkip dataSkip, IDataTake dataTake)
		{
			SqlCommand	command = new SqlCommand();
			command.CommandText = GetSelectionCriteria(InlineProcs.ctprLocation_SelectAllByCriteriaProjection, listProjection, listCriterion, listOrder, dataSkip, dataTake);
			command.CommandType = CommandType.Text;
			SqlConnection staticConnection = StaticSqlConnection;
			command.Connection = staticConnection;

			DataTable dt = new DataTable("Location");
			SqlDataAdapter sqlAdapter = new SqlDataAdapter(command);
			try
			{
				command.Parameters.Add(CtSqlParameter.Get("@ErrorCode", SqlDbType.Int, 4, ParameterDirection.Output, false, 10, 0, "", DataRowVersion.Proposed, null));

				staticConnection.Open();
				sqlAdapter.Fill(dt);

				int errorCode = (Int32)command.Parameters["@ErrorCode"].Value;
				if(errorCode > 1)
					throw new Exception("procedure ctprLocation_SelectAllByCriteriaProjection returned error code: " + errorCode );

				IDictionary<string, IList<object>> dict = new Dictionary<string, IList<object>>();
				foreach (IDataProjection projection in listProjection)
				{
					IList<object> lst = new List<object>();
					dict.Add(projection.Member, lst);
					foreach (DataRow row in dt.Rows)
					{
						if (string.Compare(projection.Member, "Id", true) == 0) lst.Add(Convert.IsDBNull(row["Id"]) ? (Int32?)null : (Int32?)row["Id"]);
						if (string.Compare(projection.Member, "Unit", true) == 0) lst.Add(Convert.IsDBNull(row["Unit"]) ? (Int32?)null : (Int32?)row["Unit"]);
						if (string.Compare(projection.Member, "PostalCode", true) == 0) lst.Add(Convert.IsDBNull(row["PostalCode"]) ? null : (string)row["PostalCode"]);
						if (string.Compare(projection.Member, "StreetName", true) == 0) lst.Add(Convert.IsDBNull(row["StreetName"]) ? null : (string)row["StreetName"]);
						if (string.Compare(projection.Member, "Link", true) == 0) lst.Add(Convert.IsDBNull(row["Link"]) ? null : (string)row["Link"]);
						if (string.Compare(projection.Member, "Map", true) == 0) lst.Add(Convert.IsDBNull(row["Map"]) ? null : (string)row["Map"]);
						if (string.Compare(projection.Member, "LatLong", true) == 0) lst.Add(Convert.IsDBNull(row["LatLong"]) ? null : (string)row["LatLong"]);
					}
				}
				return dict;
			}
			catch(Exception ex)
			{
				Handle(null, ex);
				return null;
			}
			finally
			{
				staticConnection.Close();
				command.Dispose();
			}
		}

		///<Summary>
		///Select all rows by filter criteria
		///This method returns all data rows in the table using criteriaquery api Location
		///</Summary>
		///<returns>
		///IList-DAOLocation.
		///</returns>
		///<parameters>
		///IList<IDataCriterion> listCriterion, IList<IDataOrderBy> listOrder, IDataSkip dataSkip, IDataTake dataTake
		///</parameters>
		public static IList<DAOLocation> SelectAllByCriteria(IList<IDataCriterion> listCriterion, IList<IDataOrderBy> listOrder, IDataSkip dataSkip, IDataTake dataTake)
		{
			SqlCommand	command = new SqlCommand();
			command.CommandText = GetSelectionCriteria(InlineProcs.ctprLocation_SelectAllByCriteria, null, listCriterion, listOrder, dataSkip, dataTake);
			command.CommandType = CommandType.Text;
			SqlConnection staticConnection = StaticSqlConnection;
			command.Connection = staticConnection;

			DataTable dt = new DataTable("Location");
			SqlDataAdapter sqlAdapter = new SqlDataAdapter(command);
			try
			{
				command.Parameters.Add(CtSqlParameter.Get("@ErrorCode", SqlDbType.Int, 4, ParameterDirection.Output, false, 10, 0, "", DataRowVersion.Proposed, null));

				staticConnection.Open();
				sqlAdapter.Fill(dt);

				int errorCode = (Int32)command.Parameters["@ErrorCode"].Value;
				if(errorCode > 1)
					throw new Exception("procedure ctprLocation_SelectAllByCriteria returned error code: " + errorCode );

				List<DAOLocation> objList = new List<DAOLocation>();
				if(dt.Rows.Count > 0)
				{
					foreach(DataRow row in dt.Rows)
					{
						DAOLocation retObj = new DAOLocation();
						retObj._id					 = Convert.IsDBNull(row["Id"]) ? (Int32?)null : (Int32?)row["Id"];
						retObj._unit					 = Convert.IsDBNull(row["Unit"]) ? (Int32?)null : (Int32?)row["Unit"];
						retObj._postalCode					 = Convert.IsDBNull(row["PostalCode"]) ? null : (string)row["PostalCode"];
						retObj._streetName					 = Convert.IsDBNull(row["StreetName"]) ? null : (string)row["StreetName"];
						retObj._link					 = Convert.IsDBNull(row["Link"]) ? null : (string)row["Link"];
						retObj._map					 = Convert.IsDBNull(row["Map"]) ? null : (string)row["Map"];
						retObj._latLong					 = Convert.IsDBNull(row["LatLong"]) ? null : (string)row["LatLong"];
						objList.Add(retObj);
					}
				}
				return objList;
			}
			catch(Exception ex)
			{
				Handle(null, ex);
				return null;
			}
			finally
			{
				staticConnection.Close();
				command.Dispose();
			}
		}

		///<Summary>
		///Select count of all rows using criteriaquery api
		///This method returns all data rows in the table using criteriaquery api Location
		///</Summary>
		///<returns>
		///Int32
		///</returns>
		///<parameters>
		///IList<IDataCriterion> listCriterion
		///</parameters>
		public static Int32 SelectAllByCriteriaCount(IList<IDataCriterion> listCriterion)
		{
			SqlCommand	command = new SqlCommand();
			command.CommandText = GetSelectionCriteria(InlineProcs.ctprLocation_SelectAllByCriteriaCount, null, listCriterion, null);
			command.CommandType = CommandType.Text;
			SqlConnection staticConnection = StaticSqlConnection;
			command.Connection = staticConnection;

			try
			{
				command.Parameters.Add(CtSqlParameter.Get("@ErrorCode", SqlDbType.Int, 4, ParameterDirection.Output, false, 10, 0, "", DataRowVersion.Proposed, null));

				staticConnection.Open();
				Int32 retCount = (Int32)command.ExecuteScalar();

				int errorCode = (Int32)command.Parameters["@ErrorCode"].Value;
				if(errorCode > 1)
					throw new Exception("procedure ctprLocation_SelectAllByCriteriaCount returned error code: " + errorCode );

				return retCount;
			}
			catch(Exception ex)
			{
				Handle(null, ex);
				return -1;
			}
			finally
			{
				staticConnection.Close();
				command.Dispose();
			}
		}

		///<Summary>
		///Update one row by primary key(s)
		///This method allows the object to update itself in the table Location based on its primary key(s)
		///</Summary>
		///<returns>
		///void
		///</returns>
		///<parameters>
		///
		///</parameters>
		public virtual void Update()
		{
			SqlCommand	command = new SqlCommand();
			command.CommandText = InlineProcs.ctprLocation_UpdateOne;
			command.CommandType = CommandType.Text;
			command.Connection = _connectionProvider.Connection;
			command.Transaction = _connectionProvider.CurrentTransaction;

			try
			{
				command.Parameters.Add(CtSqlParameter.Get("@Map", SqlDbType.Text, 2147483647, ParameterDirection.Input, false, 0, 0, "", DataRowVersion.Proposed, (object)_map?? (object)DBNull.Value));
				command.Parameters.Add(CtSqlParameter.Get("@Id", SqlDbType.Int, 4, ParameterDirection.InputOutput, false, 10, 0, "", DataRowVersion.Proposed, (object)_id?? (object)DBNull.Value));
				command.Parameters.Add(CtSqlParameter.Get("@Unit", SqlDbType.Int, 4, ParameterDirection.InputOutput, false, 10, 0, "", DataRowVersion.Proposed, (object)_unit?? (object)DBNull.Value));
				command.Parameters.Add(CtSqlParameter.Get("@PostalCode", SqlDbType.Char, 6, ParameterDirection.InputOutput, false, 0, 0, "", DataRowVersion.Proposed, (object)_postalCode?? (object)DBNull.Value));
				command.Parameters.Add(CtSqlParameter.Get("@StreetName", SqlDbType.NVarChar, 255, ParameterDirection.InputOutput, false, 0, 0, "", DataRowVersion.Proposed, (object)_streetName?? (object)DBNull.Value));
				command.Parameters.Add(CtSqlParameter.Get("@Link", SqlDbType.Char, 17, ParameterDirection.InputOutput, false, 0, 0, "", DataRowVersion.Proposed, (object)_link?? (object)DBNull.Value));
				command.Parameters.Add(CtSqlParameter.Get("@LatLong", SqlDbType.Char, 25, ParameterDirection.InputOutput, false, 0, 0, "", DataRowVersion.Proposed, (object)_latLong?? (object)DBNull.Value));
				command.Parameters.Add(CtSqlParameter.Get("@ErrorCode", SqlDbType.Int, 4, ParameterDirection.Output, false, 10, 0, "", DataRowVersion.Proposed, _errorCode));

				command.ExecuteNonQuery();

				_errorCode = (Int32)command.Parameters["@ErrorCode"].Value;
				if(_errorCode > 1)
					throw new Exception("procedure ctprLocation_UpdateOne returned error code: " + _errorCode );

				_id					 = Convert.IsDBNull(command.Parameters["@Id"].Value) ? (Int32?)null : (Int32?)command.Parameters["@Id"].Value;
				_unit					 = Convert.IsDBNull(command.Parameters["@Unit"].Value) ? (Int32?)null : (Int32?)command.Parameters["@Unit"].Value;
				_postalCode					 = Convert.IsDBNull(command.Parameters["@PostalCode"].Value) ? null : (string)command.Parameters["@PostalCode"].Value;
				_streetName					 = Convert.IsDBNull(command.Parameters["@StreetName"].Value) ? null : (string)command.Parameters["@StreetName"].Value;
				_link					 = Convert.IsDBNull(command.Parameters["@Link"].Value) ? null : (string)command.Parameters["@Link"].Value;
				_latLong					 = Convert.IsDBNull(command.Parameters["@LatLong"].Value) ? null : (string)command.Parameters["@LatLong"].Value;

			}
			catch(Exception ex)
			{
				Handle(this, ex);
			}
			finally
			{
				command.Dispose();
			}
		}

		#endregion

		#region member properties

		public Int32? Id
		{
			get
			{
				return _id;
			}
			set
			{
				_id = value;
			}
		}

		public Int32? Unit
		{
			get
			{
				return _unit;
			}
			set
			{
				_unit = value;
			}
		}

		public string PostalCode
		{
			get
			{
				return _postalCode;
			}
			set
			{
				_postalCode = value;
			}
		}

		public string StreetName
		{
			get
			{
				return _streetName;
			}
			set
			{
				_streetName = value;
			}
		}

		public string Link
		{
			get
			{
				return _link;
			}
			set
			{
				_link = value;
			}
		}

		public string Map
		{
			get
			{
				return _map;
			}
			set
			{
				_map = value;
			}
		}

		public string LatLong
		{
			get
			{
				return _latLong;
			}
			set
			{
				_latLong = value;
			}
		}

		public Int32? ErrorCode
		{
			get
			{
				return _errorCode;
			}
		}

		#endregion
	}
}

#region inline sql procs
namespace AAF.DataObjects
{
	public partial class InlineProcs
	{
		internal static string ctprLocation_SelectOne = @"
			-- Select one row based on the primary key(s)
			SET NOCOUNT ON
			-- selects all rows from the table
			-- returning the error code if any
			SELECT 
			[Id]
			,[Unit]
			,[PostalCode]
			,[StreetName]
			,[Link]
			,[Map]
			,[LatLong]
			FROM [administrator].[Location]
			WHERE 
			[Id] = @Id
			-- returning the error code if any
			SELECT @ErrorCode = @@ERROR
			";

		internal static string ctprLocation_DeleteOne = @"
			-- Delete a row based on the primary key(s)
			SET NOCOUNT ON
			-- delete all matching from the table
			-- returning the error code if any
			DELETE [administrator].[Location]
			WHERE 
			[Id] = @Id
			-- returning the error code if any
			SELECT @ErrorCode = @@ERROR
			";

		internal static string ctprLocation_InsertOne = @"
			-- Insert a new row
			SET NOCOUNT ON
			-- inserts a new row into the table
			-- returning the error code if any, and the identity field, if any
			INSERT [administrator].[Location]
			(
			[Unit]
			,[PostalCode]
			,[StreetName]
			,[Link]
			,[Map]
			,[LatLong]
			)
			VALUES
			(
			@Unit
			,@PostalCode
			,@StreetName
			,@Link
			,@Map
			,@LatLong
			)
			SELECT 
			@Id = [Id]
			,@Unit = [Unit]
			,@PostalCode = [PostalCode]
			,@StreetName = [StreetName]
			,@Link = [Link]
			,@LatLong = [LatLong]
			FROM [administrator].[Location]
			WHERE 
			[Id] = SCOPE_IDENTITY()
			-- returning the error code if any
			SELECT @ErrorCode = @@ERROR
			";

		internal static string ctprLocation_SelectAll = @"
			-- Select All rows
			SET NOCOUNT ON
			-- selects all rows from the table
			-- returning the error code if any
			SELECT 
			[Id]
			,[Unit]
			,[PostalCode]
			,[StreetName]
			,[Link]
			,[Map]
			,[LatLong]
			FROM [administrator].[Location]
			-- returning the error code if any
			SELECT @ErrorCode = @@ERROR
			";

		internal static string ctprLocation_SelectAllCount = @"
			
			SET NOCOUNT ON
			-- selects count of all rows from the table
			-- returning the error code if any
			SELECT COUNT(*)
			FROM [administrator].[Location]
			-- returning the error code if any
			SELECT @ErrorCode = @@ERROR
			";

		internal static string ctprLocation_SelectAllByCriteriaProjection = @"
			
			SET NOCOUNT ON
			-- selects all rows from the table by criteria
			-- returning the error code if any
			SELECT 
			##STARTFIELDS##
			##ENDFIELDS##
			FROM [administrator].[Location]
			##CRITERIA##
			-- returning the error code if any
			SELECT @ErrorCode = @@ERROR
			";

		internal static string ctprLocation_SelectAllByCriteria = @"
			
			SET NOCOUNT ON
			-- selects all rows from the table by criteria
			-- returning the error code if any
			SELECT 
			[Id]
			,[Unit]
			,[PostalCode]
			,[StreetName]
			,[Link]
			,[Map]
			,[LatLong]
			FROM [administrator].[Location]
			##CRITERIA##
			-- returning the error code if any
			SELECT @ErrorCode = @@ERROR
			";

		internal static string ctprLocation_SelectAllByCriteriaCount = @"
			
			SET NOCOUNT ON
			-- selects count of all rows from the table according to criteria
			-- returning the error code if any
			SELECT COUNT(*)
			FROM [administrator].[Location]
			##CRITERIA##
			-- returning the error code if any
			SELECT @ErrorCode = @@ERROR
			";

		internal static string ctprLocation_UpdateOne = @"
			-- Update one row based on the primary key(s)
			SET NOCOUNT ON
			-- updates a row in the table based on the primary key
			-- returning the error code if any, and the identity field, if any
			
			UPDATE [administrator].[Location]
			SET
			[Unit] = @Unit
			,[PostalCode] = @PostalCode
			,[StreetName] = @StreetName
			,[Link] = @Link
			,[Map] = @Map
			,[LatLong] = @LatLong
			WHERE 
			[Id] = @Id
			SELECT 
			@Id = [Id]
			,@Unit = [Unit]
			,@PostalCode = [PostalCode]
			,@StreetName = [StreetName]
			,@Link = [Link]
			,@LatLong = [LatLong]
			FROM [administrator].[Location]
			WHERE 
			[Id] = @Id
			-- returning the error code if any
			SELECT @ErrorCode = @@ERROR
			";

	}
}
#endregion
