/*************************************************************
** Class generated by CodeTrigger, Version 6.3.0.4
** This class was generated on 2020-08-01 3:54:27 AM
** Changes to this file may cause incorrect behaviour and will be lost if the code is regenerated
**************************************************************/
using System;
using System.Data;
using System.Data.SqlClient;
using System.Collections.Generic;
using AAF.DataObjects.Interfaces;

namespace AAF.DataObjects
{
	public partial class DAORestaurantLanguage : zAAFConn_BaseData
	{
		#region member variables
		protected Int32? _id;
		protected Int32? _restaurantId;
		protected Int16? _languageId;
		protected byte? _state;
		protected Int32? _errorCode;
		#endregion

		#region class methods
		public DAORestaurantLanguage()
		{
		}
		///<Summary>
		///Select one row by primary key(s)
		///This method returns one row from the table RestaurantLanguage based on the primary key(s)
		///</Summary>
		///<returns>
		///DAORestaurantLanguage
		///</returns>
		///<parameters>
		///Int32? id
		///</parameters>
		public static DAORestaurantLanguage SelectOne(Int32? id)
		{
			SqlCommand	command = new SqlCommand();
			command.CommandText = InlineProcs.ctprRestaurantLanguage_SelectOne;
			command.CommandType = CommandType.Text;
			SqlConnection staticConnection = StaticSqlConnection;
			command.Connection = staticConnection;

			DataTable dt = new DataTable("RestaurantLanguage");
			SqlDataAdapter sqlAdapter = new SqlDataAdapter(command);
			try
			{
				command.Parameters.Add(CtSqlParameter.Get("@Id", SqlDbType.Int, 4, ParameterDirection.Input, false, 10, 0, "", DataRowVersion.Proposed, (object)id?? (object)DBNull.Value));
				command.Parameters.Add(CtSqlParameter.Get("@ErrorCode", SqlDbType.Int, 4, ParameterDirection.Output, false, 10, 0, "", DataRowVersion.Proposed, null));

				staticConnection.Open();
				sqlAdapter.Fill(dt);

				int errorCode = (Int32)command.Parameters["@ErrorCode"].Value;
				if(errorCode > 1)
					throw new Exception("procedure ctprRestaurantLanguage_SelectOne returned error code: " + errorCode );

				DAORestaurantLanguage retObj = null;
				if(dt.Rows.Count > 0)
				{
					retObj = new DAORestaurantLanguage();
					retObj._id					 = Convert.IsDBNull(dt.Rows[0]["Id"]) ? (Int32?)null : (Int32?)dt.Rows[0]["Id"];
					retObj._restaurantId					 = Convert.IsDBNull(dt.Rows[0]["RestaurantId"]) ? (Int32?)null : (Int32?)dt.Rows[0]["RestaurantId"];
					retObj._languageId					 = Convert.IsDBNull(dt.Rows[0]["LanguageId"]) ? (Int16?)null : (Int16?)dt.Rows[0]["LanguageId"];
					retObj._state					 = Convert.IsDBNull(dt.Rows[0]["State"]) ? (byte?)null : (byte?)dt.Rows[0]["State"];
				}
				return retObj;
			}
			catch(Exception ex)
			{
				Handle(null, ex);
				return null;
			}
			finally
			{
				staticConnection.Close();
				command.Dispose();
			}
		}

		///<Summary>
		///Delete one row by primary key(s)
		///this method allows the object to delete itself from the table RestaurantLanguage based on its primary key
		///</Summary>
		///<returns>
		///void
		///</returns>
		///<parameters>
		///
		///</parameters>
		public virtual void Delete()
		{
			SqlCommand	command = new SqlCommand();
			command.CommandText = InlineProcs.ctprRestaurantLanguage_DeleteOne;
			command.CommandType = CommandType.Text;
			command.Connection = _connectionProvider.Connection;
			command.Transaction = _connectionProvider.CurrentTransaction;

			try
			{
				command.Parameters.Add(CtSqlParameter.Get("@Id", SqlDbType.Int, 4, ParameterDirection.Input, false, 10, 0, "", DataRowVersion.Proposed, (object)_id?? (object)DBNull.Value));
				command.Parameters.Add(CtSqlParameter.Get("@ErrorCode", SqlDbType.Int, 4, ParameterDirection.Output, false, 10, 0, "", DataRowVersion.Proposed, _errorCode));

				command.ExecuteNonQuery();

				_errorCode = (Int32)command.Parameters["@ErrorCode"].Value;
				if(_errorCode > 1)
					throw new Exception("procedure ctprRestaurantLanguage_DeleteOne returned error code: " + _errorCode );

			}
			catch(Exception ex)
			{
				Handle(this, ex);
			}
			finally
			{
				command.Dispose();
			}
		}

		///<Summary>
		///Select all rows by foreign key
		///This method returns all data rows in the table RestaurantLanguage based on a foreign key
		///</Summary>
		///<returns>
		///IList-DAORestaurantLanguage.
		///</returns>
		///<parameters>
		///Int32? restaurantId
		///</parameters>
		public static IList<DAORestaurantLanguage> SelectAllByRestaurantId(Int32? restaurantId)
		{
			SqlCommand	command = new SqlCommand();
			command.CommandText = InlineProcs.ctprRestaurantLanguage_SelectAllByRestaurantId;
			command.CommandType = CommandType.Text;
			SqlConnection staticConnection = StaticSqlConnection;
			command.Connection = staticConnection;

			DataTable dt = new DataTable("RestaurantLanguage");
			SqlDataAdapter sqlAdapter = new SqlDataAdapter(command);
			try
			{
				command.Parameters.Add(CtSqlParameter.Get("@RestaurantId", SqlDbType.Int, 4, ParameterDirection.Input, false, 10, 0, "", DataRowVersion.Proposed, (object)restaurantId?? (object)DBNull.Value));
				command.Parameters.Add(CtSqlParameter.Get("@ErrorCode", SqlDbType.Int, 4, ParameterDirection.Output, false, 10, 0, "", DataRowVersion.Proposed, null));

				staticConnection.Open();
				sqlAdapter.Fill(dt);

				int errorCode = (Int32)command.Parameters["@ErrorCode"].Value;
				if(errorCode > 1)
					throw new Exception("procedure ctprRestaurantLanguage_SelectAllByRestaurantId returned error code: " + errorCode );

				List<DAORestaurantLanguage> objList = new List<DAORestaurantLanguage>();
				if(dt.Rows.Count > 0)
				{
					foreach(DataRow row in dt.Rows)
					{
						DAORestaurantLanguage retObj = new DAORestaurantLanguage();
						retObj._id					 = Convert.IsDBNull(row["Id"]) ? (Int32?)null : (Int32?)row["Id"];
						retObj._restaurantId					 = Convert.IsDBNull(row["RestaurantId"]) ? (Int32?)null : (Int32?)row["RestaurantId"];
						retObj._languageId					 = Convert.IsDBNull(row["LanguageId"]) ? (Int16?)null : (Int16?)row["LanguageId"];
						retObj._state					 = Convert.IsDBNull(row["State"]) ? (byte?)null : (byte?)row["State"];
						objList.Add(retObj);
					}
				}
				return objList;
			}
			catch(Exception ex)
			{
				Handle(null, ex);
				return null;
			}
			finally
			{
				staticConnection.Close();
				command.Dispose();
			}
		}

		///<Summary>
		///</Summary>
		///<returns>
		///Int32
		///</returns>
		///<parameters>
		///Int32? restaurantId
		///</parameters>
		public static Int32 SelectAllByRestaurantIdCount(Int32? restaurantId)
		{
			SqlCommand	command = new SqlCommand();
			command.CommandText = InlineProcs.ctprRestaurantLanguage_SelectAllByRestaurantIdCount;
			command.CommandType = CommandType.Text;
			SqlConnection staticConnection = StaticSqlConnection;
			command.Connection = staticConnection;

			try
			{
				command.Parameters.Add(CtSqlParameter.Get("@RestaurantId", SqlDbType.Int, 4, ParameterDirection.Input, false, 10, 0, "", DataRowVersion.Proposed, (object)restaurantId?? (object)DBNull.Value));
				command.Parameters.Add(CtSqlParameter.Get("@ErrorCode", SqlDbType.Int, 4, ParameterDirection.Output, false, 10, 0, "", DataRowVersion.Proposed, null));

				staticConnection.Open();
				Int32 retCount = (Int32)command.ExecuteScalar();

				int errorCode = (Int32)command.Parameters["@ErrorCode"].Value;
				if(errorCode > 1)
					throw new Exception("procedure ctprRestaurantLanguage_SelectAllByRestaurantIdCount returned error code: " + errorCode );

				return retCount;
			}
			catch(Exception ex)
			{
				Handle(null, ex);
				return -1;
			}
			finally
			{
				staticConnection.Close();
				command.Dispose();
			}
		}

		///<Summary>
		///Delete all by foreign key
		///This method deletes all rows in the table RestaurantLanguage with a given foreign key
		///</Summary>
		///<returns>
		///void
		///</returns>
		///<parameters>
		///zAAFConn_TxConnectionProvider connectionProvider, Int32? restaurantId
		///</parameters>
		public static void DeleteAllByRestaurantId(zAAFConn_TxConnectionProvider connectionProvider, Int32? restaurantId)
		{
			SqlCommand	command = new SqlCommand();
			command.CommandText = InlineProcs.ctprRestaurantLanguage_DeleteAllByRestaurantId;
			command.CommandType = CommandType.Text;
			command.Connection = connectionProvider.Connection;
			command.Transaction = connectionProvider.CurrentTransaction;

			try
			{
				command.Parameters.Add(CtSqlParameter.Get("@RestaurantId", SqlDbType.Int, 4, ParameterDirection.Input, false, 10, 0, "", DataRowVersion.Proposed, (object)restaurantId?? (object)DBNull.Value));
				command.Parameters.Add(CtSqlParameter.Get("@ErrorCode", SqlDbType.Int, 4, ParameterDirection.Output, false, 10, 0, "", DataRowVersion.Proposed, null));

				command.ExecuteNonQuery();

				int errorCode = (Int32)command.Parameters["@ErrorCode"].Value;
				if(errorCode > 1)
					throw new Exception("procedure ctprRestaurantLanguage_DeleteAllByRestaurantId returned error code: " + errorCode );

			}
			catch(Exception ex)
			{
				Handle(null, ex);
			}
			finally
			{
				command.Dispose();
			}
		}

		///<Summary>
		///Select all rows by foreign key
		///This method returns all data rows in the table RestaurantLanguage based on a foreign key
		///</Summary>
		///<returns>
		///IList-DAORestaurantLanguage.
		///</returns>
		///<parameters>
		///Int16? languageId
		///</parameters>
		public static IList<DAORestaurantLanguage> SelectAllByLanguageId(Int16? languageId)
		{
			SqlCommand	command = new SqlCommand();
			command.CommandText = InlineProcs.ctprRestaurantLanguage_SelectAllByLanguageId;
			command.CommandType = CommandType.Text;
			SqlConnection staticConnection = StaticSqlConnection;
			command.Connection = staticConnection;

			DataTable dt = new DataTable("RestaurantLanguage");
			SqlDataAdapter sqlAdapter = new SqlDataAdapter(command);
			try
			{
				command.Parameters.Add(CtSqlParameter.Get("@LanguageId", SqlDbType.SmallInt, 2, ParameterDirection.Input, false, 5, 0, "", DataRowVersion.Proposed, (object)languageId?? (object)DBNull.Value));
				command.Parameters.Add(CtSqlParameter.Get("@ErrorCode", SqlDbType.Int, 4, ParameterDirection.Output, false, 10, 0, "", DataRowVersion.Proposed, null));

				staticConnection.Open();
				sqlAdapter.Fill(dt);

				int errorCode = (Int32)command.Parameters["@ErrorCode"].Value;
				if(errorCode > 1)
					throw new Exception("procedure ctprRestaurantLanguage_SelectAllByLanguageId returned error code: " + errorCode );

				List<DAORestaurantLanguage> objList = new List<DAORestaurantLanguage>();
				if(dt.Rows.Count > 0)
				{
					foreach(DataRow row in dt.Rows)
					{
						DAORestaurantLanguage retObj = new DAORestaurantLanguage();
						retObj._id					 = Convert.IsDBNull(row["Id"]) ? (Int32?)null : (Int32?)row["Id"];
						retObj._restaurantId					 = Convert.IsDBNull(row["RestaurantId"]) ? (Int32?)null : (Int32?)row["RestaurantId"];
						retObj._languageId					 = Convert.IsDBNull(row["LanguageId"]) ? (Int16?)null : (Int16?)row["LanguageId"];
						retObj._state					 = Convert.IsDBNull(row["State"]) ? (byte?)null : (byte?)row["State"];
						objList.Add(retObj);
					}
				}
				return objList;
			}
			catch(Exception ex)
			{
				Handle(null, ex);
				return null;
			}
			finally
			{
				staticConnection.Close();
				command.Dispose();
			}
		}

		///<Summary>
		///</Summary>
		///<returns>
		///Int32
		///</returns>
		///<parameters>
		///Int16? languageId
		///</parameters>
		public static Int32 SelectAllByLanguageIdCount(Int16? languageId)
		{
			SqlCommand	command = new SqlCommand();
			command.CommandText = InlineProcs.ctprRestaurantLanguage_SelectAllByLanguageIdCount;
			command.CommandType = CommandType.Text;
			SqlConnection staticConnection = StaticSqlConnection;
			command.Connection = staticConnection;

			try
			{
				command.Parameters.Add(CtSqlParameter.Get("@LanguageId", SqlDbType.SmallInt, 2, ParameterDirection.Input, false, 5, 0, "", DataRowVersion.Proposed, (object)languageId?? (object)DBNull.Value));
				command.Parameters.Add(CtSqlParameter.Get("@ErrorCode", SqlDbType.Int, 4, ParameterDirection.Output, false, 10, 0, "", DataRowVersion.Proposed, null));

				staticConnection.Open();
				Int32 retCount = (Int32)command.ExecuteScalar();

				int errorCode = (Int32)command.Parameters["@ErrorCode"].Value;
				if(errorCode > 1)
					throw new Exception("procedure ctprRestaurantLanguage_SelectAllByLanguageIdCount returned error code: " + errorCode );

				return retCount;
			}
			catch(Exception ex)
			{
				Handle(null, ex);
				return -1;
			}
			finally
			{
				staticConnection.Close();
				command.Dispose();
			}
		}

		///<Summary>
		///Delete all by foreign key
		///This method deletes all rows in the table RestaurantLanguage with a given foreign key
		///</Summary>
		///<returns>
		///void
		///</returns>
		///<parameters>
		///zAAFConn_TxConnectionProvider connectionProvider, Int16? languageId
		///</parameters>
		public static void DeleteAllByLanguageId(zAAFConn_TxConnectionProvider connectionProvider, Int16? languageId)
		{
			SqlCommand	command = new SqlCommand();
			command.CommandText = InlineProcs.ctprRestaurantLanguage_DeleteAllByLanguageId;
			command.CommandType = CommandType.Text;
			command.Connection = connectionProvider.Connection;
			command.Transaction = connectionProvider.CurrentTransaction;

			try
			{
				command.Parameters.Add(CtSqlParameter.Get("@LanguageId", SqlDbType.SmallInt, 2, ParameterDirection.Input, false, 5, 0, "", DataRowVersion.Proposed, (object)languageId?? (object)DBNull.Value));
				command.Parameters.Add(CtSqlParameter.Get("@ErrorCode", SqlDbType.Int, 4, ParameterDirection.Output, false, 10, 0, "", DataRowVersion.Proposed, null));

				command.ExecuteNonQuery();

				int errorCode = (Int32)command.Parameters["@ErrorCode"].Value;
				if(errorCode > 1)
					throw new Exception("procedure ctprRestaurantLanguage_DeleteAllByLanguageId returned error code: " + errorCode );

			}
			catch(Exception ex)
			{
				Handle(null, ex);
			}
			finally
			{
				command.Dispose();
			}
		}

		///<Summary>
		///Insert a new row
		///This method saves a new object to the table RestaurantLanguage
		///</Summary>
		///<returns>
		///void
		///</returns>
		///<parameters>
		///
		///</parameters>
		public virtual void Insert()
		{
			SqlCommand	command = new SqlCommand();
			command.CommandText = InlineProcs.ctprRestaurantLanguage_InsertOne;
			command.CommandType = CommandType.Text;
			command.Connection = _connectionProvider.Connection;
			command.Transaction = _connectionProvider.CurrentTransaction;

			try
			{
				command.Parameters.Add(CtSqlParameter.Get("@Id", SqlDbType.Int, 4, ParameterDirection.Output, false, 10, 0, "", DataRowVersion.Proposed, _id));
				command.Parameters.Add(CtSqlParameter.Get("@RestaurantId", SqlDbType.Int, 4, ParameterDirection.InputOutput, false, 10, 0, "", DataRowVersion.Proposed, (object)_restaurantId?? (object)DBNull.Value));
				command.Parameters.Add(CtSqlParameter.Get("@LanguageId", SqlDbType.SmallInt, 2, ParameterDirection.InputOutput, false, 5, 0, "", DataRowVersion.Proposed, (object)_languageId?? (object)DBNull.Value));
				command.Parameters.Add(CtSqlParameter.Get("@State", SqlDbType.TinyInt, 1, ParameterDirection.InputOutput, false, 3, 0, "", DataRowVersion.Proposed, (object)_state?? (object)DBNull.Value));
				command.Parameters.Add(CtSqlParameter.Get("@ErrorCode", SqlDbType.Int, 4, ParameterDirection.Output, false, 10, 0, "", DataRowVersion.Proposed, _errorCode));

				command.ExecuteNonQuery();

				_errorCode = (Int32)command.Parameters["@ErrorCode"].Value;
				if(_errorCode > 1)
					throw new Exception("procedure ctprRestaurantLanguage_InsertOne returned error code: " + _errorCode );

				_id					 = Convert.IsDBNull(command.Parameters["@Id"].Value) ? (Int32?)null : (Int32?)command.Parameters["@Id"].Value;
				_restaurantId					 = Convert.IsDBNull(command.Parameters["@RestaurantId"].Value) ? (Int32?)null : (Int32?)command.Parameters["@RestaurantId"].Value;
				_languageId					 = Convert.IsDBNull(command.Parameters["@LanguageId"].Value) ? (Int16?)null : (Int16?)command.Parameters["@LanguageId"].Value;
				_state					 = Convert.IsDBNull(command.Parameters["@State"].Value) ? (byte?)null : (byte?)command.Parameters["@State"].Value;

			}
			catch(Exception ex)
			{
				Handle(this, ex);
			}
			finally
			{
				command.Dispose();
			}
		}

		///<Summary>
		///Select all rows
		///This method returns all data rows in the table RestaurantLanguage
		///</Summary>
		///<returns>
		///IList-DAORestaurantLanguage.
		///</returns>
		///<parameters>
		///
		///</parameters>
		public static IList<DAORestaurantLanguage> SelectAll()
		{
			SqlCommand	command = new SqlCommand();
			command.CommandText = InlineProcs.ctprRestaurantLanguage_SelectAll;
			command.CommandType = CommandType.Text;
			SqlConnection staticConnection = StaticSqlConnection;
			command.Connection = staticConnection;

			DataTable dt = new DataTable("RestaurantLanguage");
			SqlDataAdapter sqlAdapter = new SqlDataAdapter(command);
			try
			{
				command.Parameters.Add(CtSqlParameter.Get("@ErrorCode", SqlDbType.Int, 4, ParameterDirection.Output, false, 10, 0, "", DataRowVersion.Proposed, null));

				staticConnection.Open();
				sqlAdapter.Fill(dt);

				int errorCode = (Int32)command.Parameters["@ErrorCode"].Value;
				if(errorCode > 1)
					throw new Exception("procedure ctprRestaurantLanguage_SelectAll returned error code: " + errorCode );

				List<DAORestaurantLanguage> objList = new List<DAORestaurantLanguage>();
				if(dt.Rows.Count > 0)
				{
					foreach(DataRow row in dt.Rows)
					{
						DAORestaurantLanguage retObj = new DAORestaurantLanguage();
						retObj._id					 = Convert.IsDBNull(row["Id"]) ? (Int32?)null : (Int32?)row["Id"];
						retObj._restaurantId					 = Convert.IsDBNull(row["RestaurantId"]) ? (Int32?)null : (Int32?)row["RestaurantId"];
						retObj._languageId					 = Convert.IsDBNull(row["LanguageId"]) ? (Int16?)null : (Int16?)row["LanguageId"];
						retObj._state					 = Convert.IsDBNull(row["State"]) ? (byte?)null : (byte?)row["State"];
						objList.Add(retObj);
					}
				}
				return objList;
			}
			catch(Exception ex)
			{
				Handle(null, ex);
				return null;
			}
			finally
			{
				staticConnection.Close();
				command.Dispose();
			}
		}

		///<Summary>
		///</Summary>
		///<returns>
		///Int32
		///</returns>
		///<parameters>
		///
		///</parameters>
		public static Int32 SelectAllCount()
		{
			SqlCommand	command = new SqlCommand();
			command.CommandText = InlineProcs.ctprRestaurantLanguage_SelectAllCount;
			command.CommandType = CommandType.Text;
			SqlConnection staticConnection = StaticSqlConnection;
			command.Connection = staticConnection;

			try
			{
				command.Parameters.Add(CtSqlParameter.Get("@ErrorCode", SqlDbType.Int, 4, ParameterDirection.Output, false, 10, 0, "", DataRowVersion.Proposed, null));

				staticConnection.Open();
				Int32 retCount = (Int32)command.ExecuteScalar();

				int errorCode = (Int32)command.Parameters["@ErrorCode"].Value;
				if(errorCode > 1)
					throw new Exception("procedure ctprRestaurantLanguage_SelectAllCount returned error code: " + errorCode );

				return retCount;
			}
			catch(Exception ex)
			{
				Handle(null, ex);
				return -1;
			}
			finally
			{
				staticConnection.Close();
				command.Dispose();
			}
		}

		///<Summary>
		///Select specific fields of all rows using criteriaquery api
		///This method returns specific fields of all data rows in the table using criteriaquery apiRestaurantLanguage
		///</Summary>
		///<returns>
		///IDictionary-string, IList-object..
		///</returns>
		///<parameters>
		///IList<IDataProjection> listProjection, IList<IDataCriterion> listCriterion, IList<IDataOrderBy> listOrder, IDataSkip dataSkip, IDataTake dataTake
		///</parameters>
		public static IDictionary<string, IList<object>> SelectAllByCriteriaProjection(IList<IDataProjection> listProjection, IList<IDataCriterion> listCriterion, IList<IDataOrderBy> listOrder, IDataSkip dataSkip, IDataTake dataTake)
		{
			SqlCommand	command = new SqlCommand();
			command.CommandText = GetSelectionCriteria(InlineProcs.ctprRestaurantLanguage_SelectAllByCriteriaProjection, listProjection, listCriterion, listOrder, dataSkip, dataTake);
			command.CommandType = CommandType.Text;
			SqlConnection staticConnection = StaticSqlConnection;
			command.Connection = staticConnection;

			DataTable dt = new DataTable("RestaurantLanguage");
			SqlDataAdapter sqlAdapter = new SqlDataAdapter(command);
			try
			{
				command.Parameters.Add(CtSqlParameter.Get("@ErrorCode", SqlDbType.Int, 4, ParameterDirection.Output, false, 10, 0, "", DataRowVersion.Proposed, null));

				staticConnection.Open();
				sqlAdapter.Fill(dt);

				int errorCode = (Int32)command.Parameters["@ErrorCode"].Value;
				if(errorCode > 1)
					throw new Exception("procedure ctprRestaurantLanguage_SelectAllByCriteriaProjection returned error code: " + errorCode );

				IDictionary<string, IList<object>> dict = new Dictionary<string, IList<object>>();
				foreach (IDataProjection projection in listProjection)
				{
					IList<object> lst = new List<object>();
					dict.Add(projection.Member, lst);
					foreach (DataRow row in dt.Rows)
					{
						if (string.Compare(projection.Member, "Id", true) == 0) lst.Add(Convert.IsDBNull(row["Id"]) ? (Int32?)null : (Int32?)row["Id"]);
						if (string.Compare(projection.Member, "RestaurantId", true) == 0) lst.Add(Convert.IsDBNull(row["RestaurantId"]) ? (Int32?)null : (Int32?)row["RestaurantId"]);
						if (string.Compare(projection.Member, "LanguageId", true) == 0) lst.Add(Convert.IsDBNull(row["LanguageId"]) ? (Int16?)null : (Int16?)row["LanguageId"]);
						if (string.Compare(projection.Member, "State", true) == 0) lst.Add(Convert.IsDBNull(row["State"]) ? (byte?)null : (byte?)row["State"]);
					}
				}
				return dict;
			}
			catch(Exception ex)
			{
				Handle(null, ex);
				return null;
			}
			finally
			{
				staticConnection.Close();
				command.Dispose();
			}
		}

		///<Summary>
		///Select all rows by filter criteria
		///This method returns all data rows in the table using criteriaquery api RestaurantLanguage
		///</Summary>
		///<returns>
		///IList-DAORestaurantLanguage.
		///</returns>
		///<parameters>
		///IList<IDataCriterion> listCriterion, IList<IDataOrderBy> listOrder, IDataSkip dataSkip, IDataTake dataTake
		///</parameters>
		public static IList<DAORestaurantLanguage> SelectAllByCriteria(IList<IDataCriterion> listCriterion, IList<IDataOrderBy> listOrder, IDataSkip dataSkip, IDataTake dataTake)
		{
			SqlCommand	command = new SqlCommand();
			command.CommandText = GetSelectionCriteria(InlineProcs.ctprRestaurantLanguage_SelectAllByCriteria, null, listCriterion, listOrder, dataSkip, dataTake);
			command.CommandType = CommandType.Text;
			SqlConnection staticConnection = StaticSqlConnection;
			command.Connection = staticConnection;

			DataTable dt = new DataTable("RestaurantLanguage");
			SqlDataAdapter sqlAdapter = new SqlDataAdapter(command);
			try
			{
				command.Parameters.Add(CtSqlParameter.Get("@ErrorCode", SqlDbType.Int, 4, ParameterDirection.Output, false, 10, 0, "", DataRowVersion.Proposed, null));

				staticConnection.Open();
				sqlAdapter.Fill(dt);

				int errorCode = (Int32)command.Parameters["@ErrorCode"].Value;
				if(errorCode > 1)
					throw new Exception("procedure ctprRestaurantLanguage_SelectAllByCriteria returned error code: " + errorCode );

				List<DAORestaurantLanguage> objList = new List<DAORestaurantLanguage>();
				if(dt.Rows.Count > 0)
				{
					foreach(DataRow row in dt.Rows)
					{
						DAORestaurantLanguage retObj = new DAORestaurantLanguage();
						retObj._id					 = Convert.IsDBNull(row["Id"]) ? (Int32?)null : (Int32?)row["Id"];
						retObj._restaurantId					 = Convert.IsDBNull(row["RestaurantId"]) ? (Int32?)null : (Int32?)row["RestaurantId"];
						retObj._languageId					 = Convert.IsDBNull(row["LanguageId"]) ? (Int16?)null : (Int16?)row["LanguageId"];
						retObj._state					 = Convert.IsDBNull(row["State"]) ? (byte?)null : (byte?)row["State"];
						objList.Add(retObj);
					}
				}
				return objList;
			}
			catch(Exception ex)
			{
				Handle(null, ex);
				return null;
			}
			finally
			{
				staticConnection.Close();
				command.Dispose();
			}
		}

		///<Summary>
		///Select count of all rows using criteriaquery api
		///This method returns all data rows in the table using criteriaquery api RestaurantLanguage
		///</Summary>
		///<returns>
		///Int32
		///</returns>
		///<parameters>
		///IList<IDataCriterion> listCriterion
		///</parameters>
		public static Int32 SelectAllByCriteriaCount(IList<IDataCriterion> listCriterion)
		{
			SqlCommand	command = new SqlCommand();
			command.CommandText = GetSelectionCriteria(InlineProcs.ctprRestaurantLanguage_SelectAllByCriteriaCount, null, listCriterion, null);
			command.CommandType = CommandType.Text;
			SqlConnection staticConnection = StaticSqlConnection;
			command.Connection = staticConnection;

			try
			{
				command.Parameters.Add(CtSqlParameter.Get("@ErrorCode", SqlDbType.Int, 4, ParameterDirection.Output, false, 10, 0, "", DataRowVersion.Proposed, null));

				staticConnection.Open();
				Int32 retCount = (Int32)command.ExecuteScalar();

				int errorCode = (Int32)command.Parameters["@ErrorCode"].Value;
				if(errorCode > 1)
					throw new Exception("procedure ctprRestaurantLanguage_SelectAllByCriteriaCount returned error code: " + errorCode );

				return retCount;
			}
			catch(Exception ex)
			{
				Handle(null, ex);
				return -1;
			}
			finally
			{
				staticConnection.Close();
				command.Dispose();
			}
		}

		///<Summary>
		///Update one row by primary key(s)
		///This method allows the object to update itself in the table RestaurantLanguage based on its primary key(s)
		///</Summary>
		///<returns>
		///void
		///</returns>
		///<parameters>
		///
		///</parameters>
		public virtual void Update()
		{
			SqlCommand	command = new SqlCommand();
			command.CommandText = InlineProcs.ctprRestaurantLanguage_UpdateOne;
			command.CommandType = CommandType.Text;
			command.Connection = _connectionProvider.Connection;
			command.Transaction = _connectionProvider.CurrentTransaction;

			try
			{
				command.Parameters.Add(CtSqlParameter.Get("@Id", SqlDbType.Int, 4, ParameterDirection.InputOutput, false, 10, 0, "", DataRowVersion.Proposed, (object)_id?? (object)DBNull.Value));
				command.Parameters.Add(CtSqlParameter.Get("@RestaurantId", SqlDbType.Int, 4, ParameterDirection.InputOutput, false, 10, 0, "", DataRowVersion.Proposed, (object)_restaurantId?? (object)DBNull.Value));
				command.Parameters.Add(CtSqlParameter.Get("@LanguageId", SqlDbType.SmallInt, 2, ParameterDirection.InputOutput, false, 5, 0, "", DataRowVersion.Proposed, (object)_languageId?? (object)DBNull.Value));
				command.Parameters.Add(CtSqlParameter.Get("@State", SqlDbType.TinyInt, 1, ParameterDirection.InputOutput, false, 3, 0, "", DataRowVersion.Proposed, (object)_state?? (object)DBNull.Value));
				command.Parameters.Add(CtSqlParameter.Get("@ErrorCode", SqlDbType.Int, 4, ParameterDirection.Output, false, 10, 0, "", DataRowVersion.Proposed, _errorCode));

				command.ExecuteNonQuery();

				_errorCode = (Int32)command.Parameters["@ErrorCode"].Value;
				if(_errorCode > 1)
					throw new Exception("procedure ctprRestaurantLanguage_UpdateOne returned error code: " + _errorCode );

				_id					 = Convert.IsDBNull(command.Parameters["@Id"].Value) ? (Int32?)null : (Int32?)command.Parameters["@Id"].Value;
				_restaurantId					 = Convert.IsDBNull(command.Parameters["@RestaurantId"].Value) ? (Int32?)null : (Int32?)command.Parameters["@RestaurantId"].Value;
				_languageId					 = Convert.IsDBNull(command.Parameters["@LanguageId"].Value) ? (Int16?)null : (Int16?)command.Parameters["@LanguageId"].Value;
				_state					 = Convert.IsDBNull(command.Parameters["@State"].Value) ? (byte?)null : (byte?)command.Parameters["@State"].Value;

			}
			catch(Exception ex)
			{
				Handle(this, ex);
			}
			finally
			{
				command.Dispose();
			}
		}

		#endregion

		#region member properties

		public Int32? Id
		{
			get
			{
				return _id;
			}
			set
			{
				_id = value;
			}
		}

		public Int32? RestaurantId
		{
			get
			{
				return _restaurantId;
			}
			set
			{
				_restaurantId = value;
			}
		}

		public Int16? LanguageId
		{
			get
			{
				return _languageId;
			}
			set
			{
				_languageId = value;
			}
		}

		public byte? State
		{
			get
			{
				return _state;
			}
			set
			{
				_state = value;
			}
		}

		public Int32? ErrorCode
		{
			get
			{
				return _errorCode;
			}
		}

		#endregion
	}
}

#region inline sql procs
namespace AAF.DataObjects
{
	public partial class InlineProcs
	{
		internal static string ctprRestaurantLanguage_SelectOne = @"
			-- Select one row based on the primary key(s)
			SET NOCOUNT ON
			-- selects all rows from the table
			-- returning the error code if any
			SELECT 
			[Id]
			,[RestaurantId]
			,[LanguageId]
			,[State]
			FROM [administrator].[RestaurantLanguage]
			WHERE 
			[Id] = @Id
			-- returning the error code if any
			SELECT @ErrorCode = @@ERROR
			";

		internal static string ctprRestaurantLanguage_DeleteOne = @"
			-- Delete a row based on the primary key(s)
			SET NOCOUNT ON
			-- delete all matching from the table
			-- returning the error code if any
			DELETE [administrator].[RestaurantLanguage]
			WHERE 
			[Id] = @Id
			-- returning the error code if any
			SELECT @ErrorCode = @@ERROR
			";

		internal static string ctprRestaurantLanguage_SelectAllByRestaurantId = @"
			-- Select all rows based on a foreign key
			SET NOCOUNT ON
			-- selects all rows from the table
			-- returning the error code if any
			SELECT 
			[Id]
			,[RestaurantId]
			,[LanguageId]
			,[State]
			FROM [administrator].[RestaurantLanguage]
			WHERE 
			[RestaurantId] = @RestaurantId OR ([RestaurantId] IS NULL AND @RestaurantId IS NULL)
			-- returning the error code if any
			SELECT @ErrorCode = @@ERROR
			";

		internal static string ctprRestaurantLanguage_SelectAllByRestaurantIdCount = @"
			-- Get count of rows returnable by this query
			SET NOCOUNT ON
			-- selects count of all rows from the table
			-- returning the error code if any
			SELECT COUNT(*)
			FROM [administrator].[RestaurantLanguage]
			WHERE 
			[RestaurantId] = @RestaurantId OR ([RestaurantId] IS NULL AND @RestaurantId IS NULL)
			-- returning the error code if any
			SELECT @ErrorCode = @@ERROR
			";

		internal static string ctprRestaurantLanguage_DeleteAllByRestaurantId = @"
			
			SET NOCOUNT ON
			-- delete all matching from the table
			-- returning the error code if any
			DELETE [administrator].[RestaurantLanguage]
			WHERE 
			[RestaurantId] = @RestaurantId OR ([RestaurantId] IS NULL AND @RestaurantId IS NULL)
			-- returning the error code if any
			SELECT @ErrorCode = @@ERROR
			";

		internal static string ctprRestaurantLanguage_SelectAllByLanguageId = @"
			-- Select all rows based on a foreign key
			SET NOCOUNT ON
			-- selects all rows from the table
			-- returning the error code if any
			SELECT 
			[Id]
			,[RestaurantId]
			,[LanguageId]
			,[State]
			FROM [administrator].[RestaurantLanguage]
			WHERE 
			[LanguageId] = @LanguageId OR ([LanguageId] IS NULL AND @LanguageId IS NULL)
			-- returning the error code if any
			SELECT @ErrorCode = @@ERROR
			";

		internal static string ctprRestaurantLanguage_SelectAllByLanguageIdCount = @"
			-- Get count of rows returnable by this query
			SET NOCOUNT ON
			-- selects count of all rows from the table
			-- returning the error code if any
			SELECT COUNT(*)
			FROM [administrator].[RestaurantLanguage]
			WHERE 
			[LanguageId] = @LanguageId OR ([LanguageId] IS NULL AND @LanguageId IS NULL)
			-- returning the error code if any
			SELECT @ErrorCode = @@ERROR
			";

		internal static string ctprRestaurantLanguage_DeleteAllByLanguageId = @"
			
			SET NOCOUNT ON
			-- delete all matching from the table
			-- returning the error code if any
			DELETE [administrator].[RestaurantLanguage]
			WHERE 
			[LanguageId] = @LanguageId OR ([LanguageId] IS NULL AND @LanguageId IS NULL)
			-- returning the error code if any
			SELECT @ErrorCode = @@ERROR
			";

		internal static string ctprRestaurantLanguage_InsertOne = @"
			-- Insert a new row
			SET NOCOUNT ON
			-- inserts a new row into the table
			-- returning the error code if any, and the identity field, if any
			INSERT [administrator].[RestaurantLanguage]
			(
			[RestaurantId]
			,[LanguageId]
			,[State]
			)
			VALUES
			(
			@RestaurantId
			,@LanguageId
			,@State
			)
			SELECT 
			@Id = [Id]
			,@RestaurantId = [RestaurantId]
			,@LanguageId = [LanguageId]
			,@State = [State]
			FROM [administrator].[RestaurantLanguage]
			WHERE 
			[Id] = SCOPE_IDENTITY()
			-- returning the error code if any
			SELECT @ErrorCode = @@ERROR
			";

		internal static string ctprRestaurantLanguage_SelectAll = @"
			-- Select All rows
			SET NOCOUNT ON
			-- selects all rows from the table
			-- returning the error code if any
			SELECT 
			[Id]
			,[RestaurantId]
			,[LanguageId]
			,[State]
			FROM [administrator].[RestaurantLanguage]
			-- returning the error code if any
			SELECT @ErrorCode = @@ERROR
			";

		internal static string ctprRestaurantLanguage_SelectAllCount = @"
			
			SET NOCOUNT ON
			-- selects count of all rows from the table
			-- returning the error code if any
			SELECT COUNT(*)
			FROM [administrator].[RestaurantLanguage]
			-- returning the error code if any
			SELECT @ErrorCode = @@ERROR
			";

		internal static string ctprRestaurantLanguage_SelectAllByCriteriaProjection = @"
			
			SET NOCOUNT ON
			-- selects all rows from the table by criteria
			-- returning the error code if any
			SELECT 
			##STARTFIELDS##
			##ENDFIELDS##
			FROM [administrator].[RestaurantLanguage]
			##CRITERIA##
			-- returning the error code if any
			SELECT @ErrorCode = @@ERROR
			";

		internal static string ctprRestaurantLanguage_SelectAllByCriteria = @"
			
			SET NOCOUNT ON
			-- selects all rows from the table by criteria
			-- returning the error code if any
			SELECT 
			[Id]
			,[RestaurantId]
			,[LanguageId]
			,[State]
			FROM [administrator].[RestaurantLanguage]
			##CRITERIA##
			-- returning the error code if any
			SELECT @ErrorCode = @@ERROR
			";

		internal static string ctprRestaurantLanguage_SelectAllByCriteriaCount = @"
			
			SET NOCOUNT ON
			-- selects count of all rows from the table according to criteria
			-- returning the error code if any
			SELECT COUNT(*)
			FROM [administrator].[RestaurantLanguage]
			##CRITERIA##
			-- returning the error code if any
			SELECT @ErrorCode = @@ERROR
			";

		internal static string ctprRestaurantLanguage_UpdateOne = @"
			-- Update one row based on the primary key(s)
			SET NOCOUNT ON
			-- updates a row in the table based on the primary key
			-- returning the error code if any, and the identity field, if any
			
			UPDATE [administrator].[RestaurantLanguage]
			SET
			[RestaurantId] = @RestaurantId
			,[LanguageId] = @LanguageId
			,[State] = @State
			WHERE 
			[Id] = @Id
			SELECT 
			@Id = [Id]
			,@RestaurantId = [RestaurantId]
			,@LanguageId = [LanguageId]
			,@State = [State]
			FROM [administrator].[RestaurantLanguage]
			WHERE 
			[Id] = @Id
			-- returning the error code if any
			SELECT @ErrorCode = @@ERROR
			";

	}
}
#endregion
