/*************************************************************
** Class generated by CodeTrigger, Version 6.3.0.4
** This class was generated on 2020-08-01 3:54:27 AM
**************************************************************/

using System;

namespace AAF.DataObjects.Interfaces
{
	public interface IDataCriterion
	{
		string ToSql();
	}

	public interface IDataOrderBy
	{
		string ToSql();
	}

	public interface IDataSkip
	{
		string ToSql();
	}

	public interface IDataTake
	{
		string ToSql();
	}

	public interface IDataProjection
	{
		string Member { get; set; }
		string ToSql();
	}

}
