/*************************************************************
** Class generated by CodeTrigger, Version 6.3.0.4
** This class was generated on 2020-08-01 3:54:27 AM
** Changes to this file may cause incorrect behaviour and will be lost if the code is regenerated
**************************************************************/
using System;
using System.Collections.Generic;
using System.Xml.Serialization;
using AAF.DataObjects;
using AAF.DataObjects.Interfaces;
using AAF.BusinessObjects.Interfaces;

namespace AAF.BusinessObjects
{
	///<Summary>
	///Class definition
	///This is the definition of the class BOAppSetting.
	///</Summary>
	public partial class BOAppSetting : zAAFConn_BaseBusiness, IQueryableCollection
	{
		#region member variables
		protected Int32? _id;
		protected Int32? _nameKey;
		protected Int32? _descriptionKey;
		protected bool _isDirty = false;
		/*collection member objects*******************/
		/*********************************************/
		#endregion

		#region class methods
		///<Summary>
		///Constructor
		///This is the default constructor
		///</Summary>
		///<returns>
		///void
		///</returns>
		///<parameters>
		///
		///</parameters>
		public BOAppSetting()
		{
		}

		///<Summary>
		///Constructor
		///Constructor using primary key(s)
		///</Summary>
		///<returns>
		///void
		///</returns>
		///<parameters>
		///Int32 id
		///</parameters>
		public BOAppSetting(Int32 id)
		{
			try
			{
				DAOAppSetting daoAppSetting = DAOAppSetting.SelectOne(id);
				_id = daoAppSetting.Id;
				_nameKey = daoAppSetting.NameKey;
				_descriptionKey = daoAppSetting.DescriptionKey;
			}
			catch
			{
				throw;
			}
		}

		///<Summary>
		///Constructor
		///This constructor initializes the business object from its respective data object
		///</Summary>
		///<returns>
		///void
		///</returns>
		///<parameters>
		///DAOAppSetting
		///</parameters>
		protected internal BOAppSetting(DAOAppSetting daoAppSetting)
		{
			try
			{
				_id = daoAppSetting.Id;
				_nameKey = daoAppSetting.NameKey;
				_descriptionKey = daoAppSetting.DescriptionKey;
			}
			catch
			{
				throw;
			}
		}

		///<Summary>
		///SaveNew
		///This method persists a new AppSetting record to the store
		///</Summary>
		///<returns>
		///void
		///</returns>
		///<parameters>
		///
		///</parameters>
		public virtual void SaveNew()
		{
			DAOAppSetting daoAppSetting = new DAOAppSetting();
			RegisterDataObject(daoAppSetting);
			BeginTransaction("savenewBOAppSetting");
			try
			{
				daoAppSetting.Id = _id;
				daoAppSetting.NameKey = _nameKey;
				daoAppSetting.DescriptionKey = _descriptionKey;
				daoAppSetting.Insert();
				CommitTransaction();
				
				_id = daoAppSetting.Id;
				_nameKey = daoAppSetting.NameKey;
				_descriptionKey = daoAppSetting.DescriptionKey;
				_isDirty = false;
			}
			catch(Exception ex)
			{
				RollbackTransaction("savenewBOAppSetting");
				Handle(this, ex);
			}
		}
		
		///<Summary>
		///Update
		///This method updates one AppSetting record in the store
		///</Summary>
		///<returns>
		///void
		///</returns>
		///<parameters>
		///BOAppSetting
		///</parameters>
		public virtual void Update()
		{
			DAOAppSetting daoAppSetting = new DAOAppSetting();
			RegisterDataObject(daoAppSetting);
			BeginTransaction("updateBOAppSetting");
			try
			{
				daoAppSetting.Id = _id;
				daoAppSetting.NameKey = _nameKey;
				daoAppSetting.DescriptionKey = _descriptionKey;
				daoAppSetting.Update();
				CommitTransaction();
				
				_id = daoAppSetting.Id;
				_nameKey = daoAppSetting.NameKey;
				_descriptionKey = daoAppSetting.DescriptionKey;
				_isDirty = false;
			}
			catch(Exception ex)
			{
				RollbackTransaction("updateBOAppSetting");
				Handle(this, ex);
			}
		}
		///<Summary>
		///Delete
		///This method deletes one AppSetting record from the store
		///</Summary>
		///<returns>
		///void
		///</returns>
		///<parameters>
		///
		///</parameters>
		public virtual void Delete()
		{
			DAOAppSetting daoAppSetting = new DAOAppSetting();
			RegisterDataObject(daoAppSetting);
			BeginTransaction("deleteBOAppSetting");
			try
			{
				daoAppSetting.Id = _id;
				daoAppSetting.Delete();
				CommitTransaction();
			}
			catch(Exception ex)
			{
				RollbackTransaction("deleteBOAppSetting");
				Handle(this, ex);
			}
		}
		
		///<Summary>
		///AppSettingCollection
		///This method returns the collection of BOAppSetting objects
		///</Summary>
		///<returns>
		///List[BOAppSetting]
		///</returns>
		///<parameters>
		///
		///</parameters>
		public static IList<BOAppSetting> AppSettingCollection()
		{
			try
			{
				IList<BOAppSetting> boAppSettingCollection = new List<BOAppSetting>();
				IList<DAOAppSetting> daoAppSettingCollection = DAOAppSetting.SelectAll();
			
				foreach(DAOAppSetting daoAppSetting in daoAppSettingCollection)
					boAppSettingCollection.Add(new BOAppSetting(daoAppSetting));
			
				return boAppSettingCollection;
			}
			catch(Exception ex)
			{
				Handle(null, ex);
				return null;
			}
		}
		
		
		///<Summary>
		///AppSettingCollectionCount
		///This method returns the collection count of BOAppSetting objects
		///</Summary>
		///<returns>
		///Int32
		///</returns>
		///<parameters>
		///
		///</parameters>
		public static Int32 AppSettingCollectionCount()
		{
			try
			{
				Int32 objCount = DAOAppSetting.SelectAllCount();
				return objCount;
			}
			catch(Exception ex)
			{
				Handle(null, ex);
				return -1;
			}
		}
		
		
		///<Summary>
		///Projections
		///This method returns the collection of projections, ordered and filtered by optional criteria
		///</Summary>
		///<returns>
		///List<BOAppSetting>
		///</returns>
		///<parameters>
		///ICriteria icriteria
		///</parameters>
		public virtual IDictionary<string, IList<object>> Projections(object o)
		{
			try
			{
				ICriteria icriteria = (ICriteria)o;
				IList<IDataProjection> lstDataProjection = (icriteria == null) ? null : icriteria.ListDataProjection();
				IList<IDataCriterion> lstDataCriteria = (icriteria == null) ? null : icriteria.ListDataCriteria();
				IList<IDataOrderBy> lstDataOrder = (icriteria == null) ? null : icriteria.ListDataOrder();
				IDataTake dataTake = (icriteria == null) ? null : icriteria.DataTake();
				IDataSkip dataSkip = (icriteria == null) ? null : icriteria.DataSkip();
				IDictionary<string, IList<object>> retObj = DAOAppSetting.SelectAllByCriteriaProjection(lstDataProjection, lstDataCriteria, lstDataOrder, dataSkip, dataTake);
				return retObj;
			}
			catch(Exception ex)
			{
				Handle(this, ex);
				return null;
			}
		}
		
		
		///<Summary>
		///AppSettingCollection<T>
		///This method implements the IQueryable Collection<T> method, returning a collection of BOAppSetting objects, filtered by optional criteria
		///</Summary>
		///<returns>
		///IList<T>
		///</returns>
		///<parameters>
		///object o
		///</parameters>
		public virtual IList<T> Collection<T>(object o)
		{
			try
			{
				ICriteria icriteria = (ICriteria)o;
				IList<T> boAppSettingCollection = new List<T>();
				IList<IDataCriterion> lstDataCriteria = (icriteria == null) ? null : icriteria.ListDataCriteria();
				IList<IDataOrderBy> lstDataOrder = (icriteria == null) ? null : icriteria.ListDataOrder();
				IDataTake dataTake = (icriteria == null) ? null : icriteria.DataTake();
				IDataSkip dataSkip = (icriteria == null) ? null : icriteria.DataSkip();
				IList<DAOAppSetting> daoAppSettingCollection = DAOAppSetting.SelectAllByCriteria(lstDataCriteria, lstDataOrder, dataSkip, dataTake);
			
				foreach(DAOAppSetting resdaoAppSetting in daoAppSettingCollection)
					boAppSettingCollection.Add((T)(object)new BOAppSetting(resdaoAppSetting));
			
				return boAppSettingCollection;
			}
			catch(Exception ex)
			{
				Handle(this, ex);
				return null;
			}
		}
		
		
		///<Summary>
		///AppSettingCollectionCount
		///This method implements the IQueryable CollectionCount method, returning a collection count of BOAppSetting objects, filtered by optional criteria
		///</Summary>
		///<returns>
		///Int32
		///</returns>
		///<parameters>
		///object o
		///</parameters>
		public virtual Int32 CollectionCount(object o)
		{
			try
			{
				ICriteria icriteria = (ICriteria)o;
				IList<IDataCriterion> lstDataCriteria = (icriteria == null) ? null : icriteria.ListDataCriteria();
				Int32 objCount = DAOAppSetting.SelectAllByCriteriaCount(lstDataCriteria);
				return objCount;
			}
			catch(Exception ex)
			{
				Handle(this, ex);
				return -1;
			}
		}
		
		#endregion

		#region member properties
		
		public virtual Int32? Id
		{
			get
			{
				 return _id;
			}
			set
			{
				_id = value;
				_isDirty = true;
			}
		}
		
		public virtual Int32? NameKey
		{
			get
			{
				 return _nameKey;
			}
			set
			{
				_nameKey = value;
				_isDirty = true;
			}
		}
		
		public virtual Int32? DescriptionKey
		{
			get
			{
				 return _descriptionKey;
			}
			set
			{
				_descriptionKey = value;
				_isDirty = true;
			}
		}
		
		[XmlIgnore]
		public virtual object Repository
		{
			get {	return null;	}
			set	{	}
		}
		
		public virtual bool IsDirty
		{
			get
			{
				 return _isDirty;
			}
			set
			{
				_isDirty = value;
			}
		}
		#endregion
	}
}
