/*************************************************************
** Class generated by CodeTrigger, Version 6.3.0.4
** This class was generated on 2020-08-01 3:54:27 AM
** Changes to this file may cause incorrect behaviour and will be lost if the code is regenerated
**************************************************************/
using System;
using System.Collections.Generic;
using System.Xml.Serialization;
using AAF.DataObjects;
using AAF.DataObjects.Interfaces;
using AAF.BusinessObjects.Interfaces;

namespace AAF.BusinessObjects
{
	///<Summary>
	///Class definition
	///This is the definition of the class BOItem.
	///</Summary>
	public partial class BOItem : zAAFConn_BaseBusiness, IQueryableCollection
	{
		#region member variables
		protected Int32? _id;
		protected Int32? _restaurantId;
		protected decimal? _price;
		protected bool? _isExtra;
		protected byte? _stateId;
		protected Int32? _nameKey;
		protected Int32? _descriptionKey;
		protected bool _isDirty = false;
		/*collection member objects*******************/
		/*********************************************/
		#endregion

		#region class methods
		///<Summary>
		///Constructor
		///This is the default constructor
		///</Summary>
		///<returns>
		///void
		///</returns>
		///<parameters>
		///
		///</parameters>
		public BOItem()
		{
		}

		///<Summary>
		///Constructor
		///Constructor using primary key(s)
		///</Summary>
		///<returns>
		///void
		///</returns>
		///<parameters>
		///Int32 id
		///</parameters>
		public BOItem(Int32 id)
		{
			try
			{
				DAOItem daoItem = DAOItem.SelectOne(id);
				_id = daoItem.Id;
				_restaurantId = daoItem.RestaurantId;
				_price = daoItem.Price;
				_isExtra = daoItem.IsExtra;
				_stateId = daoItem.StateId;
				_nameKey = daoItem.NameKey;
				_descriptionKey = daoItem.DescriptionKey;
			}
			catch
			{
				throw;
			}
		}

		///<Summary>
		///Constructor
		///This constructor initializes the business object from its respective data object
		///</Summary>
		///<returns>
		///void
		///</returns>
		///<parameters>
		///DAOItem
		///</parameters>
		protected internal BOItem(DAOItem daoItem)
		{
			try
			{
				_id = daoItem.Id;
				_restaurantId = daoItem.RestaurantId;
				_price = daoItem.Price;
				_isExtra = daoItem.IsExtra;
				_stateId = daoItem.StateId;
				_nameKey = daoItem.NameKey;
				_descriptionKey = daoItem.DescriptionKey;
			}
			catch
			{
				throw;
			}
		}

		///<Summary>
		///SaveNew
		///This method persists a new Item record to the store
		///</Summary>
		///<returns>
		///void
		///</returns>
		///<parameters>
		///
		///</parameters>
		public virtual void SaveNew()
		{
			DAOItem daoItem = new DAOItem();
			RegisterDataObject(daoItem);
			BeginTransaction("savenewBOItem");
			try
			{
				daoItem.RestaurantId = _restaurantId;
				daoItem.Price = _price;
				daoItem.IsExtra = _isExtra;
				daoItem.StateId = _stateId;
				daoItem.NameKey = _nameKey;
				daoItem.DescriptionKey = _descriptionKey;
				daoItem.Insert();
				CommitTransaction();
				
				_id = daoItem.Id;
				_restaurantId = daoItem.RestaurantId;
				_price = daoItem.Price;
				_isExtra = daoItem.IsExtra;
				_stateId = daoItem.StateId;
				_nameKey = daoItem.NameKey;
				_descriptionKey = daoItem.DescriptionKey;
				_isDirty = false;
			}
			catch(Exception ex)
			{
				RollbackTransaction("savenewBOItem");
				Handle(this, ex);
			}
		}
		
		///<Summary>
		///Update
		///This method updates one Item record in the store
		///</Summary>
		///<returns>
		///void
		///</returns>
		///<parameters>
		///BOItem
		///</parameters>
		public virtual void Update()
		{
			DAOItem daoItem = new DAOItem();
			RegisterDataObject(daoItem);
			BeginTransaction("updateBOItem");
			try
			{
				daoItem.Id = _id;
				daoItem.RestaurantId = _restaurantId;
				daoItem.Price = _price;
				daoItem.IsExtra = _isExtra;
				daoItem.StateId = _stateId;
				daoItem.NameKey = _nameKey;
				daoItem.DescriptionKey = _descriptionKey;
				daoItem.Update();
				CommitTransaction();
				
				_id = daoItem.Id;
				_restaurantId = daoItem.RestaurantId;
				_price = daoItem.Price;
				_isExtra = daoItem.IsExtra;
				_stateId = daoItem.StateId;
				_nameKey = daoItem.NameKey;
				_descriptionKey = daoItem.DescriptionKey;
				_isDirty = false;
			}
			catch(Exception ex)
			{
				RollbackTransaction("updateBOItem");
				Handle(this, ex);
			}
		}
		///<Summary>
		///Delete
		///This method deletes one Item record from the store
		///</Summary>
		///<returns>
		///void
		///</returns>
		///<parameters>
		///
		///</parameters>
		public virtual void Delete()
		{
			DAOItem daoItem = new DAOItem();
			RegisterDataObject(daoItem);
			BeginTransaction("deleteBOItem");
			try
			{
				daoItem.Id = _id;
				daoItem.Delete();
				CommitTransaction();
			}
			catch(Exception ex)
			{
				RollbackTransaction("deleteBOItem");
				Handle(this, ex);
			}
		}
		
		///<Summary>
		///ItemCollection
		///This method returns the collection of BOItem objects
		///</Summary>
		///<returns>
		///List[BOItem]
		///</returns>
		///<parameters>
		///
		///</parameters>
		public static IList<BOItem> ItemCollection()
		{
			try
			{
				IList<BOItem> boItemCollection = new List<BOItem>();
				IList<DAOItem> daoItemCollection = DAOItem.SelectAll();
			
				foreach(DAOItem daoItem in daoItemCollection)
					boItemCollection.Add(new BOItem(daoItem));
			
				return boItemCollection;
			}
			catch(Exception ex)
			{
				Handle(null, ex);
				return null;
			}
		}
		
		
		///<Summary>
		///ItemCollectionCount
		///This method returns the collection count of BOItem objects
		///</Summary>
		///<returns>
		///Int32
		///</returns>
		///<parameters>
		///
		///</parameters>
		public static Int32 ItemCollectionCount()
		{
			try
			{
				Int32 objCount = DAOItem.SelectAllCount();
				return objCount;
			}
			catch(Exception ex)
			{
				Handle(null, ex);
				return -1;
			}
		}
		
		
		///<Summary>
		///Projections
		///This method returns the collection of projections, ordered and filtered by optional criteria
		///</Summary>
		///<returns>
		///List<BOItem>
		///</returns>
		///<parameters>
		///ICriteria icriteria
		///</parameters>
		public virtual IDictionary<string, IList<object>> Projections(object o)
		{
			try
			{
				ICriteria icriteria = (ICriteria)o;
				IList<IDataProjection> lstDataProjection = (icriteria == null) ? null : icriteria.ListDataProjection();
				IList<IDataCriterion> lstDataCriteria = (icriteria == null) ? null : icriteria.ListDataCriteria();
				IList<IDataOrderBy> lstDataOrder = (icriteria == null) ? null : icriteria.ListDataOrder();
				IDataTake dataTake = (icriteria == null) ? null : icriteria.DataTake();
				IDataSkip dataSkip = (icriteria == null) ? null : icriteria.DataSkip();
				IDictionary<string, IList<object>> retObj = DAOItem.SelectAllByCriteriaProjection(lstDataProjection, lstDataCriteria, lstDataOrder, dataSkip, dataTake);
				return retObj;
			}
			catch(Exception ex)
			{
				Handle(this, ex);
				return null;
			}
		}
		
		
		///<Summary>
		///ItemCollection<T>
		///This method implements the IQueryable Collection<T> method, returning a collection of BOItem objects, filtered by optional criteria
		///</Summary>
		///<returns>
		///IList<T>
		///</returns>
		///<parameters>
		///object o
		///</parameters>
		public virtual IList<T> Collection<T>(object o)
		{
			try
			{
				ICriteria icriteria = (ICriteria)o;
				IList<T> boItemCollection = new List<T>();
				IList<IDataCriterion> lstDataCriteria = (icriteria == null) ? null : icriteria.ListDataCriteria();
				IList<IDataOrderBy> lstDataOrder = (icriteria == null) ? null : icriteria.ListDataOrder();
				IDataTake dataTake = (icriteria == null) ? null : icriteria.DataTake();
				IDataSkip dataSkip = (icriteria == null) ? null : icriteria.DataSkip();
				IList<DAOItem> daoItemCollection = DAOItem.SelectAllByCriteria(lstDataCriteria, lstDataOrder, dataSkip, dataTake);
			
				foreach(DAOItem resdaoItem in daoItemCollection)
					boItemCollection.Add((T)(object)new BOItem(resdaoItem));
			
				return boItemCollection;
			}
			catch(Exception ex)
			{
				Handle(this, ex);
				return null;
			}
		}
		
		
		///<Summary>
		///ItemCollectionCount
		///This method implements the IQueryable CollectionCount method, returning a collection count of BOItem objects, filtered by optional criteria
		///</Summary>
		///<returns>
		///Int32
		///</returns>
		///<parameters>
		///object o
		///</parameters>
		public virtual Int32 CollectionCount(object o)
		{
			try
			{
				ICriteria icriteria = (ICriteria)o;
				IList<IDataCriterion> lstDataCriteria = (icriteria == null) ? null : icriteria.ListDataCriteria();
				Int32 objCount = DAOItem.SelectAllByCriteriaCount(lstDataCriteria);
				return objCount;
			}
			catch(Exception ex)
			{
				Handle(this, ex);
				return -1;
			}
		}
		
		#endregion

		#region member properties
		
		public virtual Int32? Id
		{
			get
			{
				 return _id;
			}
			set
			{
				_id = value;
				_isDirty = true;
			}
		}
		
		public virtual Int32? RestaurantId
		{
			get
			{
				 return _restaurantId;
			}
			set
			{
				_restaurantId = value;
				_isDirty = true;
			}
		}
		
		public virtual decimal? Price
		{
			get
			{
				 return _price;
			}
			set
			{
				_price = value;
				_isDirty = true;
			}
		}
		
		public virtual bool? IsExtra
		{
			get
			{
				 return _isExtra;
			}
			set
			{
				_isExtra = value;
				_isDirty = true;
			}
		}
		
		public virtual byte? StateId
		{
			get
			{
				 return _stateId;
			}
			set
			{
				_stateId = value;
				_isDirty = true;
			}
		}
		
		public virtual Int32? NameKey
		{
			get
			{
				 return _nameKey;
			}
			set
			{
				_nameKey = value;
				_isDirty = true;
			}
		}
		
		public virtual Int32? DescriptionKey
		{
			get
			{
				 return _descriptionKey;
			}
			set
			{
				_descriptionKey = value;
				_isDirty = true;
			}
		}
		
		[XmlIgnore]
		public virtual object Repository
		{
			get {	return null;	}
			set	{	}
		}
		
		public virtual bool IsDirty
		{
			get
			{
				 return _isDirty;
			}
			set
			{
				_isDirty = value;
			}
		}
		#endregion
	}
}
