/*************************************************************
** Class generated by CodeTrigger, Version 6.3.0.4
** This class was generated on 2020-08-01 3:54:27 AM
** Changes to this file may cause incorrect behaviour and will be lost if the code is regenerated
**************************************************************/
using System;
using System.Collections.Generic;
using System.Xml.Serialization;
using AAF.DataObjects;
using AAF.DataObjects.Interfaces;
using AAF.BusinessObjects.Interfaces;

namespace AAF.BusinessObjects
{
	///<Summary>
	///Class definition
	///This is the definition of the class BORestaurantLanguage.
	///</Summary>
	public partial class BORestaurantLanguage : zAAFConn_BaseBusiness, IQueryableCollection
	{
		#region member variables
		protected Int32? _id;
		protected Int32? _restaurantId;
		protected Int16? _languageId;
		protected byte? _state;
		protected bool _isDirty = false;
		/*collection member objects*******************/
		/*********************************************/
		#endregion

		#region class methods
		///<Summary>
		///Constructor
		///This is the default constructor
		///</Summary>
		///<returns>
		///void
		///</returns>
		///<parameters>
		///
		///</parameters>
		public BORestaurantLanguage()
		{
		}

		///<Summary>
		///Constructor
		///Constructor using primary key(s)
		///</Summary>
		///<returns>
		///void
		///</returns>
		///<parameters>
		///Int32 id
		///</parameters>
		public BORestaurantLanguage(Int32 id)
		{
			try
			{
				DAORestaurantLanguage daoRestaurantLanguage = DAORestaurantLanguage.SelectOne(id);
				_id = daoRestaurantLanguage.Id;
				_restaurantId = daoRestaurantLanguage.RestaurantId;
				_languageId = daoRestaurantLanguage.LanguageId;
				_state = daoRestaurantLanguage.State;
			}
			catch
			{
				throw;
			}
		}

		///<Summary>
		///Constructor
		///This constructor initializes the business object from its respective data object
		///</Summary>
		///<returns>
		///void
		///</returns>
		///<parameters>
		///DAORestaurantLanguage
		///</parameters>
		protected internal BORestaurantLanguage(DAORestaurantLanguage daoRestaurantLanguage)
		{
			try
			{
				_id = daoRestaurantLanguage.Id;
				_restaurantId = daoRestaurantLanguage.RestaurantId;
				_languageId = daoRestaurantLanguage.LanguageId;
				_state = daoRestaurantLanguage.State;
			}
			catch
			{
				throw;
			}
		}

		///<Summary>
		///SaveNew
		///This method persists a new RestaurantLanguage record to the store
		///</Summary>
		///<returns>
		///void
		///</returns>
		///<parameters>
		///
		///</parameters>
		public virtual void SaveNew()
		{
			DAORestaurantLanguage daoRestaurantLanguage = new DAORestaurantLanguage();
			RegisterDataObject(daoRestaurantLanguage);
			BeginTransaction("savenewBORestaurantLanguage");
			try
			{
				daoRestaurantLanguage.RestaurantId = _restaurantId;
				daoRestaurantLanguage.LanguageId = _languageId;
				daoRestaurantLanguage.State = _state;
				daoRestaurantLanguage.Insert();
				CommitTransaction();
				
				_id = daoRestaurantLanguage.Id;
				_restaurantId = daoRestaurantLanguage.RestaurantId;
				_languageId = daoRestaurantLanguage.LanguageId;
				_state = daoRestaurantLanguage.State;
				_isDirty = false;
			}
			catch(Exception ex)
			{
				RollbackTransaction("savenewBORestaurantLanguage");
				Handle(this, ex);
			}
		}
		
		///<Summary>
		///Update
		///This method updates one RestaurantLanguage record in the store
		///</Summary>
		///<returns>
		///void
		///</returns>
		///<parameters>
		///BORestaurantLanguage
		///</parameters>
		public virtual void Update()
		{
			DAORestaurantLanguage daoRestaurantLanguage = new DAORestaurantLanguage();
			RegisterDataObject(daoRestaurantLanguage);
			BeginTransaction("updateBORestaurantLanguage");
			try
			{
				daoRestaurantLanguage.Id = _id;
				daoRestaurantLanguage.RestaurantId = _restaurantId;
				daoRestaurantLanguage.LanguageId = _languageId;
				daoRestaurantLanguage.State = _state;
				daoRestaurantLanguage.Update();
				CommitTransaction();
				
				_id = daoRestaurantLanguage.Id;
				_restaurantId = daoRestaurantLanguage.RestaurantId;
				_languageId = daoRestaurantLanguage.LanguageId;
				_state = daoRestaurantLanguage.State;
				_isDirty = false;
			}
			catch(Exception ex)
			{
				RollbackTransaction("updateBORestaurantLanguage");
				Handle(this, ex);
			}
		}
		///<Summary>
		///Delete
		///This method deletes one RestaurantLanguage record from the store
		///</Summary>
		///<returns>
		///void
		///</returns>
		///<parameters>
		///
		///</parameters>
		public virtual void Delete()
		{
			DAORestaurantLanguage daoRestaurantLanguage = new DAORestaurantLanguage();
			RegisterDataObject(daoRestaurantLanguage);
			BeginTransaction("deleteBORestaurantLanguage");
			try
			{
				daoRestaurantLanguage.Id = _id;
				daoRestaurantLanguage.Delete();
				CommitTransaction();
			}
			catch(Exception ex)
			{
				RollbackTransaction("deleteBORestaurantLanguage");
				Handle(this, ex);
			}
		}
		
		///<Summary>
		///RestaurantLanguageCollection
		///This method returns the collection of BORestaurantLanguage objects
		///</Summary>
		///<returns>
		///List[BORestaurantLanguage]
		///</returns>
		///<parameters>
		///
		///</parameters>
		public static IList<BORestaurantLanguage> RestaurantLanguageCollection()
		{
			try
			{
				IList<BORestaurantLanguage> boRestaurantLanguageCollection = new List<BORestaurantLanguage>();
				IList<DAORestaurantLanguage> daoRestaurantLanguageCollection = DAORestaurantLanguage.SelectAll();
			
				foreach(DAORestaurantLanguage daoRestaurantLanguage in daoRestaurantLanguageCollection)
					boRestaurantLanguageCollection.Add(new BORestaurantLanguage(daoRestaurantLanguage));
			
				return boRestaurantLanguageCollection;
			}
			catch(Exception ex)
			{
				Handle(null, ex);
				return null;
			}
		}
		
		
		///<Summary>
		///RestaurantLanguageCollectionCount
		///This method returns the collection count of BORestaurantLanguage objects
		///</Summary>
		///<returns>
		///Int32
		///</returns>
		///<parameters>
		///
		///</parameters>
		public static Int32 RestaurantLanguageCollectionCount()
		{
			try
			{
				Int32 objCount = DAORestaurantLanguage.SelectAllCount();
				return objCount;
			}
			catch(Exception ex)
			{
				Handle(null, ex);
				return -1;
			}
		}
		
		
		///<Summary>
		///Projections
		///This method returns the collection of projections, ordered and filtered by optional criteria
		///</Summary>
		///<returns>
		///List<BORestaurantLanguage>
		///</returns>
		///<parameters>
		///ICriteria icriteria
		///</parameters>
		public virtual IDictionary<string, IList<object>> Projections(object o)
		{
			try
			{
				ICriteria icriteria = (ICriteria)o;
				IList<IDataProjection> lstDataProjection = (icriteria == null) ? null : icriteria.ListDataProjection();
				IList<IDataCriterion> lstDataCriteria = (icriteria == null) ? null : icriteria.ListDataCriteria();
				IList<IDataOrderBy> lstDataOrder = (icriteria == null) ? null : icriteria.ListDataOrder();
				IDataTake dataTake = (icriteria == null) ? null : icriteria.DataTake();
				IDataSkip dataSkip = (icriteria == null) ? null : icriteria.DataSkip();
				IDictionary<string, IList<object>> retObj = DAORestaurantLanguage.SelectAllByCriteriaProjection(lstDataProjection, lstDataCriteria, lstDataOrder, dataSkip, dataTake);
				return retObj;
			}
			catch(Exception ex)
			{
				Handle(this, ex);
				return null;
			}
		}
		
		
		///<Summary>
		///RestaurantLanguageCollection<T>
		///This method implements the IQueryable Collection<T> method, returning a collection of BORestaurantLanguage objects, filtered by optional criteria
		///</Summary>
		///<returns>
		///IList<T>
		///</returns>
		///<parameters>
		///object o
		///</parameters>
		public virtual IList<T> Collection<T>(object o)
		{
			try
			{
				ICriteria icriteria = (ICriteria)o;
				IList<T> boRestaurantLanguageCollection = new List<T>();
				IList<IDataCriterion> lstDataCriteria = (icriteria == null) ? null : icriteria.ListDataCriteria();
				IList<IDataOrderBy> lstDataOrder = (icriteria == null) ? null : icriteria.ListDataOrder();
				IDataTake dataTake = (icriteria == null) ? null : icriteria.DataTake();
				IDataSkip dataSkip = (icriteria == null) ? null : icriteria.DataSkip();
				IList<DAORestaurantLanguage> daoRestaurantLanguageCollection = DAORestaurantLanguage.SelectAllByCriteria(lstDataCriteria, lstDataOrder, dataSkip, dataTake);
			
				foreach(DAORestaurantLanguage resdaoRestaurantLanguage in daoRestaurantLanguageCollection)
					boRestaurantLanguageCollection.Add((T)(object)new BORestaurantLanguage(resdaoRestaurantLanguage));
			
				return boRestaurantLanguageCollection;
			}
			catch(Exception ex)
			{
				Handle(this, ex);
				return null;
			}
		}
		
		
		///<Summary>
		///RestaurantLanguageCollectionCount
		///This method implements the IQueryable CollectionCount method, returning a collection count of BORestaurantLanguage objects, filtered by optional criteria
		///</Summary>
		///<returns>
		///Int32
		///</returns>
		///<parameters>
		///object o
		///</parameters>
		public virtual Int32 CollectionCount(object o)
		{
			try
			{
				ICriteria icriteria = (ICriteria)o;
				IList<IDataCriterion> lstDataCriteria = (icriteria == null) ? null : icriteria.ListDataCriteria();
				Int32 objCount = DAORestaurantLanguage.SelectAllByCriteriaCount(lstDataCriteria);
				return objCount;
			}
			catch(Exception ex)
			{
				Handle(this, ex);
				return -1;
			}
		}
		
		#endregion

		#region member properties
		
		public virtual Int32? Id
		{
			get
			{
				 return _id;
			}
			set
			{
				_id = value;
				_isDirty = true;
			}
		}
		
		public virtual Int32? RestaurantId
		{
			get
			{
				 return _restaurantId;
			}
			set
			{
				_restaurantId = value;
				_isDirty = true;
			}
		}
		
		public virtual Int16? LanguageId
		{
			get
			{
				 return _languageId;
			}
			set
			{
				_languageId = value;
				_isDirty = true;
			}
		}
		
		public virtual byte? State
		{
			get
			{
				 return _state;
			}
			set
			{
				_state = value;
				_isDirty = true;
			}
		}
		
		[XmlIgnore]
		public virtual object Repository
		{
			get {	return null;	}
			set	{	}
		}
		
		public virtual bool IsDirty
		{
			get
			{
				 return _isDirty;
			}
			set
			{
				_isDirty = value;
			}
		}
		#endregion
	}
}
