/*************************************************************
** Class generated by CodeTrigger, Version 6.3.0.4
** This class was generated on 2020-08-01 3:54:27 AM
** Changes to this file may cause incorrect behaviour and will be lost if the code is regenerated
**************************************************************/
using System;
using System.Collections.Generic;
using System.Xml.Serialization;
using AAF.DataObjects;
using AAF.DataObjects.Interfaces;
using AAF.BusinessObjects.Interfaces;

namespace AAF.BusinessObjects
{
	///<Summary>
	///Class definition
	///This is the definition of the class BOVietnamese.
	///</Summary>
	public partial class BOVietnamese : zAAFConn_BaseBusiness, IQueryableCollection
	{
		#region member variables
		protected Int32? _key;
		protected string _val;
		protected bool _isDirty = false;
		/*collection member objects*******************/
		/*********************************************/
		#endregion

		#region class methods
		///<Summary>
		///Constructor
		///This is the default constructor
		///</Summary>
		///<returns>
		///void
		///</returns>
		///<parameters>
		///
		///</parameters>
		public BOVietnamese()
		{
		}

		///<Summary>
		///Constructor
		///Constructor using primary key(s)
		///</Summary>
		///<returns>
		///void
		///</returns>
		///<parameters>
		///Int32 key
		///</parameters>
		public BOVietnamese(Int32 key)
		{
			try
			{
				DAOVietnamese daoVietnamese = DAOVietnamese.SelectOne(key);
				_key = daoVietnamese.Key;
				_val = daoVietnamese.Val;
			}
			catch
			{
				throw;
			}
		}

		///<Summary>
		///Constructor
		///This constructor initializes the business object from its respective data object
		///</Summary>
		///<returns>
		///void
		///</returns>
		///<parameters>
		///DAOVietnamese
		///</parameters>
		protected internal BOVietnamese(DAOVietnamese daoVietnamese)
		{
			try
			{
				_key = daoVietnamese.Key;
				_val = daoVietnamese.Val;
			}
			catch
			{
				throw;
			}
		}

		///<Summary>
		///SaveNew
		///This method persists a new Vietnamese record to the store
		///</Summary>
		///<returns>
		///void
		///</returns>
		///<parameters>
		///
		///</parameters>
		public virtual void SaveNew()
		{
			DAOVietnamese daoVietnamese = new DAOVietnamese();
			RegisterDataObject(daoVietnamese);
			BeginTransaction("savenewBOVietnamese");
			try
			{
				daoVietnamese.Key = _key;
				daoVietnamese.Val = _val;
				daoVietnamese.Insert();
				CommitTransaction();
				
				_key = daoVietnamese.Key;
				_val = daoVietnamese.Val;
				_isDirty = false;
			}
			catch(Exception ex)
			{
				RollbackTransaction("savenewBOVietnamese");
				Handle(this, ex);
			}
		}
		
		///<Summary>
		///Update
		///This method updates one Vietnamese record in the store
		///</Summary>
		///<returns>
		///void
		///</returns>
		///<parameters>
		///BOVietnamese
		///</parameters>
		public virtual void Update()
		{
			DAOVietnamese daoVietnamese = new DAOVietnamese();
			RegisterDataObject(daoVietnamese);
			BeginTransaction("updateBOVietnamese");
			try
			{
				daoVietnamese.Key = _key;
				daoVietnamese.Val = _val;
				daoVietnamese.Update();
				CommitTransaction();
				
				_key = daoVietnamese.Key;
				_val = daoVietnamese.Val;
				_isDirty = false;
			}
			catch(Exception ex)
			{
				RollbackTransaction("updateBOVietnamese");
				Handle(this, ex);
			}
		}
		///<Summary>
		///Delete
		///This method deletes one Vietnamese record from the store
		///</Summary>
		///<returns>
		///void
		///</returns>
		///<parameters>
		///
		///</parameters>
		public virtual void Delete()
		{
			DAOVietnamese daoVietnamese = new DAOVietnamese();
			RegisterDataObject(daoVietnamese);
			BeginTransaction("deleteBOVietnamese");
			try
			{
				daoVietnamese.Key = _key;
				daoVietnamese.Delete();
				CommitTransaction();
			}
			catch(Exception ex)
			{
				RollbackTransaction("deleteBOVietnamese");
				Handle(this, ex);
			}
		}
		
		///<Summary>
		///VietnameseCollection
		///This method returns the collection of BOVietnamese objects
		///</Summary>
		///<returns>
		///List[BOVietnamese]
		///</returns>
		///<parameters>
		///
		///</parameters>
		public static IList<BOVietnamese> VietnameseCollection()
		{
			try
			{
				IList<BOVietnamese> boVietnameseCollection = new List<BOVietnamese>();
				IList<DAOVietnamese> daoVietnameseCollection = DAOVietnamese.SelectAll();
			
				foreach(DAOVietnamese daoVietnamese in daoVietnameseCollection)
					boVietnameseCollection.Add(new BOVietnamese(daoVietnamese));
			
				return boVietnameseCollection;
			}
			catch(Exception ex)
			{
				Handle(null, ex);
				return null;
			}
		}
		
		
		///<Summary>
		///VietnameseCollectionCount
		///This method returns the collection count of BOVietnamese objects
		///</Summary>
		///<returns>
		///Int32
		///</returns>
		///<parameters>
		///
		///</parameters>
		public static Int32 VietnameseCollectionCount()
		{
			try
			{
				Int32 objCount = DAOVietnamese.SelectAllCount();
				return objCount;
			}
			catch(Exception ex)
			{
				Handle(null, ex);
				return -1;
			}
		}
		
		
		///<Summary>
		///Projections
		///This method returns the collection of projections, ordered and filtered by optional criteria
		///</Summary>
		///<returns>
		///List<BOVietnamese>
		///</returns>
		///<parameters>
		///ICriteria icriteria
		///</parameters>
		public virtual IDictionary<string, IList<object>> Projections(object o)
		{
			try
			{
				ICriteria icriteria = (ICriteria)o;
				IList<IDataProjection> lstDataProjection = (icriteria == null) ? null : icriteria.ListDataProjection();
				IList<IDataCriterion> lstDataCriteria = (icriteria == null) ? null : icriteria.ListDataCriteria();
				IList<IDataOrderBy> lstDataOrder = (icriteria == null) ? null : icriteria.ListDataOrder();
				IDataTake dataTake = (icriteria == null) ? null : icriteria.DataTake();
				IDataSkip dataSkip = (icriteria == null) ? null : icriteria.DataSkip();
				IDictionary<string, IList<object>> retObj = DAOVietnamese.SelectAllByCriteriaProjection(lstDataProjection, lstDataCriteria, lstDataOrder, dataSkip, dataTake);
				return retObj;
			}
			catch(Exception ex)
			{
				Handle(this, ex);
				return null;
			}
		}
		
		
		///<Summary>
		///VietnameseCollection<T>
		///This method implements the IQueryable Collection<T> method, returning a collection of BOVietnamese objects, filtered by optional criteria
		///</Summary>
		///<returns>
		///IList<T>
		///</returns>
		///<parameters>
		///object o
		///</parameters>
		public virtual IList<T> Collection<T>(object o)
		{
			try
			{
				ICriteria icriteria = (ICriteria)o;
				IList<T> boVietnameseCollection = new List<T>();
				IList<IDataCriterion> lstDataCriteria = (icriteria == null) ? null : icriteria.ListDataCriteria();
				IList<IDataOrderBy> lstDataOrder = (icriteria == null) ? null : icriteria.ListDataOrder();
				IDataTake dataTake = (icriteria == null) ? null : icriteria.DataTake();
				IDataSkip dataSkip = (icriteria == null) ? null : icriteria.DataSkip();
				IList<DAOVietnamese> daoVietnameseCollection = DAOVietnamese.SelectAllByCriteria(lstDataCriteria, lstDataOrder, dataSkip, dataTake);
			
				foreach(DAOVietnamese resdaoVietnamese in daoVietnameseCollection)
					boVietnameseCollection.Add((T)(object)new BOVietnamese(resdaoVietnamese));
			
				return boVietnameseCollection;
			}
			catch(Exception ex)
			{
				Handle(this, ex);
				return null;
			}
		}
		
		
		///<Summary>
		///VietnameseCollectionCount
		///This method implements the IQueryable CollectionCount method, returning a collection count of BOVietnamese objects, filtered by optional criteria
		///</Summary>
		///<returns>
		///Int32
		///</returns>
		///<parameters>
		///object o
		///</parameters>
		public virtual Int32 CollectionCount(object o)
		{
			try
			{
				ICriteria icriteria = (ICriteria)o;
				IList<IDataCriterion> lstDataCriteria = (icriteria == null) ? null : icriteria.ListDataCriteria();
				Int32 objCount = DAOVietnamese.SelectAllByCriteriaCount(lstDataCriteria);
				return objCount;
			}
			catch(Exception ex)
			{
				Handle(this, ex);
				return -1;
			}
		}
		
		#endregion

		#region member properties
		
		public virtual Int32? Key
		{
			get
			{
				 return _key;
			}
			set
			{
				_key = value;
				_isDirty = true;
			}
		}
		
		public virtual string Val
		{
			get
			{
				 return _val;
			}
			set
			{
				_val = value;
				_isDirty = true;
			}
		}
		
		[XmlIgnore]
		public virtual object Repository
		{
			get {	return null;	}
			set	{	}
		}
		
		public virtual bool IsDirty
		{
			get
			{
				 return _isDirty;
			}
			set
			{
				_isDirty = value;
			}
		}
		#endregion
	}
}
